# Generated by Django 5.2.15 on 2026-06-05 05:00

from collections.abc import Sequence
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial: ClassVar[bool | None] = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("accounts", "0001_initial"),
        ("applications", "0001_initial"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[("timed", "timed"), ("permanent", "permanent")],
                        default="permanent",
                        max_length=16,
                    ),
                ),
                ("grant_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("revoked", "revoked"),
                            ("expired", "expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="applications.app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="accounts.usermirror",
                    ),
                ),
            ],
            options={
                "ordering": ["app__app_key", "user__authentik_user_id", "-version"],
            },
        ),
        migrations.CreateModel(
            name="AccessGrantPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_permissions",
                        to="grants.accessgrant",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grant_permissions",
                        to="applications.permission",
                    ),
                ),
            ],
            options={
                "ordering": ["grant_id", "permission__key"],
            },
        ),
        migrations.CreateModel(
            name="AccessGrantRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_roles",
                        to="grants.accessgrant",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grant_roles",
                        to="applications.role",
                    ),
                ),
            ],
            options={
                "ordering": ["grant_id", "role__key"],
            },
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("grant_type__in", ("timed", "permanent"))),
                name="grants_access_grant_type_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("active", "revoked", "expired"))),
                name="grants_access_grant_status_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("grant_expires_at__isnull", False), ("grant_type", "timed")),
                    models.Q(("grant_expires_at__isnull", True), ("grant_type", "permanent")),
                    _connector="OR",
                ),
                name="grants_access_grant_expiration_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("user", "app"),
                name="grants_access_grant_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrantpermission",
            constraint=models.UniqueConstraint(
                fields=("grant", "permission"), name="grants_access_grant_permission_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrantrole",
            constraint=models.UniqueConstraint(
                fields=("grant", "role"), name="grants_access_grant_role_unique"
            ),
        ),
    ]
