# Generated by Codex on 2026-07-01

from collections.abc import Sequence
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


def migrate_roles_to_groups(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    access_grant_role = apps.get_model("grants", "AccessGrantRole")
    access_grant_group = apps.get_model("grants", "AccessGrantGroup")
    authorization_group = apps.get_model("applications", "AuthorizationGroup")
    role = apps.get_model("applications", "Role")

    for grant_role in access_grant_role.objects.all().iterator():
        source_role = role.objects.only("app_id", "key").get(pk=grant_role.role_id)
        group = authorization_group.objects.get(app_id=source_role.app_id, key=source_role.key)
        access_grant_group.objects.get_or_create(
            grant_id=grant_role.grant_id,
            authorization_group_id=group.id,
            defaults={"created_at": grant_role.created_at},
        )


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0009_atomic_authorization_models"),
        ("grants", "0001_initial"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name="AccessGrantGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorization_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grant_groups",
                        to="applications.authorizationgroup",
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_groups",
                        to="grants.accessgrant",
                    ),
                ),
            ],
            options={
                "ordering": ["grant_id", "authorization_group__key"],
            },
        ),
        migrations.AddField(
            model_name="accessgrantpermission",
            name="scope_key",
            field=models.CharField(default="GLOBAL", max_length=64),
        ),
        migrations.AddField(
            model_name="accessgrantpermission",
            name="source_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterModelOptions(
            name="accessgrantpermission",
            options={"ordering": ["grant_id", "permission__key", "scope_key"]},
        ),
        migrations.RunPython(migrate_roles_to_groups, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="accessgrantpermission",
            name="grants_access_grant_permission_unique",
        ),
        migrations.AddConstraint(
            model_name="accessgrantgroup",
            constraint=models.UniqueConstraint(
                fields=("grant", "authorization_group"),
                name="grants_access_grant_group_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrantpermission",
            constraint=models.UniqueConstraint(
                fields=("grant", "permission", "scope_key"),
                name="grants_access_grant_permission_unique",
            ),
        ),
    ]
