# Generated by Django 5.2.15 on 2026-07-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usermirror_options_and_more'),
        ('grants', '0005_membership_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='accounts.usermirror'),
        ),
    ]
