# ruff: noqa: ANN001, ANN201, RUF012
# pyright: reportAny=false, reportUnknownArgumentType=false, reportUnknownMemberType=false, reportUnknownParameterType=false, reportUnknownVariableType=false, reportMissingParameterType=false, reportUnannotatedClassAttribute=false
# Generated by Django 5.2.15 on 2026-09-07 15:43
import importlib

import django.db.models.deletion
from django.db import migrations, models

# SQLite 在 AddField 时重建表会丢掉 0007 安装的跨 App 守卫触发器, 因此在本迁移末尾重新安装。
_triggers = importlib.import_module(
    "easyauth.grants.migrations.0007_access_grant_relationship_triggers",
)


def reinstall_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    _triggers.drop_triggers(apps, schema_editor)
    _triggers.install_triggers(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0033_app_alias"),
        ("grants", "0007_access_grant_relationship_triggers"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentGrantPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_slug", models.CharField(max_length=128)),
                ("corp_id", models.CharField(max_length=128)),
                ("dept_id", models.CharField(max_length=128)),
                (
                    "grant_type",
                    models.CharField(
                        choices=[("timed", "timed"), ("permanent", "permanent")], max_length=16
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("reason", models.CharField(max_length=1000)),
                ("created_by_type", models.CharField(max_length=32)),
                ("created_by_id", models.CharField(max_length=128)),
                ("updated_by_type", models.CharField(max_length=32)),
                ("updated_by_id", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["app__app_key", "dept_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentGrantPolicyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "ordering": ["policy_id", "authorization_group__key"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentGrantPolicyPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope_key", models.CharField(default="GLOBAL", max_length=64)),
            ],
            options={
                "ordering": ["policy_id", "permission__key", "scope_key"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="accessgrantgroup",
            name="grants_access_grant_group_unique",
        ),
        migrations.RemoveConstraint(
            model_name="accessgrantpermission",
            name="grants_access_grant_permission_unique",
        ),
        migrations.AddField(
            model_name="accessgrantgroup",
            name="source",
            field=models.CharField(
                choices=[("user", "user"), ("department", "department")],
                default="user",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accessgrantpermission",
            name="source",
            field=models.CharField(
                choices=[("user", "user"), ("department", "department")],
                default="user",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="departmentgrantpolicy",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="department_grant_policies",
                to="applications.app",
            ),
        ),
        migrations.AddField(
            model_name="accessgrantgroup",
            name="department_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grants.departmentgrantpolicy",
            ),
        ),
        migrations.AddField(
            model_name="accessgrantpermission",
            name="department_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grants.departmentgrantpolicy",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrantgroup",
            constraint=models.UniqueConstraint(
                fields=("grant", "authorization_group", "source"),
                name="grants_access_grant_group_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrantgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ("user", "department"))),
                name="grants_access_grant_group_source_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrantpermission",
            constraint=models.UniqueConstraint(
                fields=("grant", "permission", "scope_key", "source"),
                name="grants_access_grant_permission_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrantpermission",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ("user", "department"))),
                name="grants_access_grant_permission_source_supported",
            ),
        ),
        migrations.AddField(
            model_name="departmentgrantpolicygroup",
            name="authorization_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_policy_groups",
                to="applications.authorizationgroup",
            ),
        ),
        migrations.AddField(
            model_name="departmentgrantpolicygroup",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_groups",
                to="grants.departmentgrantpolicy",
            ),
        ),
        migrations.AddField(
            model_name="departmentgrantpolicypermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_policy_permissions",
                to="applications.permission",
            ),
        ),
        migrations.AddField(
            model_name="departmentgrantpolicypermission",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_permissions",
                to="grants.departmentgrantpolicy",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentgrantpolicy",
            index=models.Index(
                fields=["source_slug", "corp_id", "dept_id"], name="grants_dept_policy_dept_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentgrantpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("grant_type__in", ("timed", "permanent"))),
                name="grants_department_policy_grant_type_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentgrantpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("expires_at__isnull", False), ("grant_type", "timed")),
                    models.Q(("expires_at__isnull", True), ("grant_type", "permanent")),
                    _connector="OR",
                ),
                name="grants_department_policy_expiry_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentgrantpolicygroup",
            constraint=models.UniqueConstraint(
                fields=("policy", "authorization_group"),
                name="grants_department_policy_group_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentgrantpolicypermission",
            constraint=models.UniqueConstraint(
                fields=("policy", "permission", "scope_key"),
                name="grants_department_policy_permission_unique",
            ),
        ),
        migrations.RunPython(reinstall_triggers, migrations.RunPython.noop),
    ]
