# Generated by Django 5.2.15 on 2026-07-05 12:39

import easyauth.config.crypto
from django.db import migrations


def _blank_plaintext_totp(apps, schema_editor):
    # 项目尚未上线: 历史明文 TOTP 种子无法被重新加密, 必须清空并强制重新绑定,
    # 避免留下无法解密的密文让 verify_totp_code 在无凭据下报错。
    _ = schema_editor
    local_admin = apps.get_model("accounts", "LocalAdminAccount")
    _ = local_admin.objects.update(totp_secret="", totp_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_localadminaccount_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localadminaccount',
            name='totp_secret',
            field=easyauth.config.crypto.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.RunPython(_blank_plaintext_totp, migrations.RunPython.noop, elidable=True),
    ]
