# Generated by Django 5.2.15 on 2026-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_localadminaccount_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='localadminaccount',
            name='totp_last_timestep',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
