# Generated by Django 5.2.15 on 2026-07-06 05:53

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('accounts', '0008_localadminaccount_totp_last_timestep'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddField(
            model_name='usermirror',
            name='department_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
