# Generated by Django 5.2.16 on 2026-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_dingtalkdirectorysyncstate_generation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dingtalkusermirror',
            index=models.Index(fields=['source_slug', 'corp_id', 'manager_userid'], name='accounts_dt_user_manager_idx'),
        ),
        migrations.AddIndex(
            model_name='usermirror',
            index=models.Index(fields=['dingtalk_corp_id', 'dingtalk_userid'], name='accounts_user_dingtalk_idx'),
        ),
    ]
