# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_usermirror_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usermirror",
            index=models.Index(
                fields=["status", "updated_at", "id"],
                name="accounts_user_retention_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dingtalkusermirror",
            index=models.Index(
                fields=["status", "departed_at", "id"],
                name="accounts_dt_user_retention_idx",
            ),
        ),
    ]
