# Generated by Django 5.2.15 on 2026-09-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_retention_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermirror',
            name='is_console_admin',
            field=models.BooleanField(default=False, help_text='EasyAuth 内控制台管理员的唯一落库标志; 与 Authentik 超管组检查取并集。'),
        ),
    ]
