# Generated by Django 5.2.15 on 2026-09-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_usermirror_is_console_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcSessionBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('authentik_user_id', models.CharField(db_index=True, max_length=128)),
                ('sid', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
