# Generated by Django 5.2.15 on 2026-09-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_usermirror_name_pinyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermirror',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
