# Generated by Django 5.2.15 on 2026-07-06 05:53

import django.db.models.deletion
from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial: ClassVar[bool | None] = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('accounts', '0009_usermirror_department_changed_at'),
        ('applications', '0019_integrationsettings_dingtalk_agent_id_and_more'),
        ('teams', '0001_initial'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HandoverTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offboard', 'offboard'), ('transfer', 'transfer')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=16)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_tasks', to='accounts.usermirror')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HandoverGrantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(blank=True, max_length=64)),
                ('grant_type', models.CharField(blank=True, max_length=16)),
                ('grant_expires_at', models.DateTimeField(blank=True, null=True)),
                ('selected', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_grant_items', to='applications.app')),
                ('authorization_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handover_grant_items', to='applications.authorizationgroup')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handover_grant_items', to='applications.permission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_items', to='lifecycle.handovertask')),
            ],
            options={
                'ordering': ['task_id', 'app__app_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HandoverAppAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('previewed', 'previewed'), ('executing', 'executing'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('preview_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_actions', to='applications.app')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_receiving_actions', to='accounts.usermirror')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_actions', to='lifecycle.handovertask')),
            ],
            options={
                'ordering': ['task_id', 'app__app_key'],
            },
        ),
        migrations.CreateModel(
            name='HandoverTeamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pending', 'pending'), ('assign_leader', 'assign_leader'), ('deactivate', 'deactivate')], default='pending', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_items', to='lifecycle.handovertask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_items', to='teams.team')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_team_items', to='accounts.usermirror')),
            ],
            options={
                'ordering': ['task_id', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(blank=True, max_length=64)),
                ('grant_type', models.CharField(default='permanent', max_length=16)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_template_items', to='applications.app')),
                ('authorization_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_template_items', to='applications.authorizationgroup')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_template_items', to='applications.permission')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lifecycle.onboardingtemplate')),
            ],
            options={
                'ordering': ['template_id', 'app__app_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_diff', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_plans', to='lifecycle.onboardingtemplate')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_plan', to='lifecycle.handovertask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='handovertask',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('offboard', 'transfer'))), name='lifecycle_task_kind_supported'),
        ),
        migrations.AddConstraint(
            model_name='handovertask',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'in_progress', 'completed', 'cancelled'))), name='lifecycle_task_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='handovertask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'in_progress'))), fields=('subject_user',), name='lifecycle_task_one_open_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='handovergrantitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'done', 'skipped'))), name='lifecycle_grant_item_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='handovergrantitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorization_group__isnull', False), ('permission__isnull', True)), models.Q(('authorization_group__isnull', True), ('permission__isnull', False)), _connector='OR'), name='lifecycle_grant_item_target_shape'),
        ),
        migrations.AddConstraint(
            model_name='handoverappaction',
            constraint=models.UniqueConstraint(fields=('task', 'app'), name='lifecycle_action_unique_per_task_app'),
        ),
        migrations.AddConstraint(
            model_name='handoverappaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'previewed', 'executing', 'done', 'failed', 'skipped'))), name='lifecycle_action_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='handoverteamitem',
            constraint=models.UniqueConstraint(fields=('task', 'team'), name='lifecycle_team_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='handoverteamitem',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('pending', 'assign_leader', 'deactivate'))), name='lifecycle_team_item_action_supported'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplateitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorization_group__isnull', False), ('permission__isnull', True)), models.Q(('authorization_group__isnull', True), ('permission__isnull', False)), _connector='OR'), name='lifecycle_template_item_target_shape'),
        ),
    ]
