# Generated by Django 5.2.15 on 2026-07-10 03:37

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from collections.abc import Sequence

    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.operations.base import Operation


def populate_handover_snapshots(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    _ = schema_editor
    HandoverAppAction = apps.get_model("lifecycle", "HandoverAppAction")
    HandoverGrantItem = apps.get_model("lifecycle", "HandoverGrantItem")
    for action in HandoverAppAction.objects.select_related("app"):
        action.app_key_snapshot = action.app.app_key
        action.app_name_snapshot = action.app.name
        action.app_catalog_version_snapshot = action.app.catalog_version
        action.save(
            update_fields=[
                "app_key_snapshot",
                "app_name_snapshot",
                "app_catalog_version_snapshot",
            ],
        )
    for item in HandoverGrantItem.objects.select_related(
        "app",
        "authorization_group",
        "permission",
    ):
        item.app_key_snapshot = item.app.app_key
        item.app_name_snapshot = item.app.name
        item.app_catalog_version_snapshot = item.app.catalog_version
        if item.authorization_group_id is not None:
            item.target_kind_snapshot = "group"
            item.target_key_snapshot = item.authorization_group.key
            item.target_name_snapshot = item.authorization_group.name
        else:
            item.target_kind_snapshot = "permission"
            item.target_key_snapshot = item.permission.key
            item.target_name_snapshot = item.permission.name
        item.save(
            update_fields=[
                "app_key_snapshot",
                "app_name_snapshot",
                "app_catalog_version_snapshot",
                "target_kind_snapshot",
                "target_key_snapshot",
                "target_name_snapshot",
            ],
        )


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("accounts", "0011_dingtalkdirectorysyncstate_generation"),
        ("applications", "0021_canonicalize_manifest_content_hash"),
        ("grants", "0005_membership_expiration"),
        ("lifecycle", "0001_initial"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.RemoveConstraint(
            model_name="handoverappaction",
            name="lifecycle_action_status_supported",
        ),
        migrations.RemoveConstraint(
            model_name="handovergrantitem",
            name="lifecycle_grant_item_target_shape",
        ),
        migrations.AddField(
            model_name="handoverappaction",
            name="app_key_snapshot",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="handoverappaction",
            name="app_catalog_version_snapshot",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handoverappaction",
            name="app_name_snapshot",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="handoverappaction",
            name="async_status_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="handoverappaction",
            name="async_poll_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handoverappaction",
            name="execution_policy",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="handoverappaction",
            name="execution_to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handover_executions",
                to="accounts.usermirror",
            ),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="app_key_snapshot",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="app_catalog_version_snapshot",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="app_name_snapshot",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="source_grant_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="source_grant_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="target_key_snapshot",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="target_kind_snapshot",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="handovergrantitem",
            name="target_name_snapshot",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="transferplan",
            name="confirmed_add_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="transferplan",
            name="confirmed_revoke_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="handoverappaction",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handover_actions",
                to="applications.app",
            ),
        ),
        migrations.AlterField(
            model_name="handoverappaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("previewed", "previewed"),
                    ("executing", "executing"),
                    ("async_pending", "async_pending"),
                    ("done", "done"),
                    ("failed", "failed"),
                    ("skipped", "skipped"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="handovergrantitem",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handover_grant_items",
                to="applications.app",
            ),
        ),
        migrations.AlterField(
            model_name="handovergrantitem",
            name="authorization_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handover_grant_items",
                to="applications.authorizationgroup",
            ),
        ),
        migrations.AlterField(
            model_name="handovergrantitem",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handover_grant_items",
                to="applications.permission",
            ),
        ),
        migrations.RunPython(populate_handover_snapshots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="handoverappaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "pending",
                            "previewed",
                            "executing",
                            "async_pending",
                            "done",
                            "failed",
                            "skipped",
                        ),
                    )
                ),
                name="lifecycle_action_status_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="handovergrantitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_kind_snapshot__in", ("group", "permission"))),
                name="lifecycle_grant_item_target_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingtemplateitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("duration_days__isnull", True), ("grant_type", "permanent")),
                    models.Q(("duration_days__isnull", False), ("grant_type", "timed")),
                    _connector="OR",
                ),
                name="lifecycle_template_item_expiration_shape",
            ),
        ),
    ]
