# Generated by Django 5.2.15 on 2026-07-26 18:35
# ruff: noqa: ANN001,ANN201,E501,Q000,RUF012

import django.db.models.deletion
from django.db import migrations, models


def fail_if_existing_transfer_plans_need_unprovable_revision_binding(apps, _schema_editor):
    TransferPlan = apps.get_model("lifecycle", "TransferPlan")
    existing = TransferPlan.objects.exclude(new_template_id=None)
    count = existing.count()
    if count:
        sample_ids = list(existing.order_by("id").values_list("id", flat=True)[:10])
        message = (
            "EA-AUD-008 迁移拒绝绑定无法证明模板修订的历史转岗计划: "
            f"count={count}, sample_ids={sample_ids}"
        )
        raise RuntimeError(message)


def copy_existing_templates_to_revisions(apps, _schema_editor):
    OnboardingTemplate = apps.get_model("lifecycle", "OnboardingTemplate")
    OnboardingTemplateItem = apps.get_model("lifecycle", "OnboardingTemplateItem")
    OnboardingTemplateRevision = apps.get_model("lifecycle", "OnboardingTemplateRevision")
    OnboardingTemplateRevisionItem = apps.get_model(
        "lifecycle",
        "OnboardingTemplateRevisionItem",
    )

    for template in OnboardingTemplate.objects.order_by("id"):
        revision = OnboardingTemplateRevision.objects.create(
            template=template,
            revision=1,
            name_snapshot=template.name,
            description_snapshot=template.description,
            is_active=template.is_active,
        )
        for item in OnboardingTemplateItem.objects.filter(template=template).order_by("id"):
            OnboardingTemplateRevisionItem.objects.create(
                revision=revision,
                app_id=item.app_id,
                authorization_group_id=item.authorization_group_id,
                permission_id=item.permission_id,
                scope_key=item.scope_key,
                grant_type=item.grant_type,
                duration_days=item.duration_days,
            )
        template.current_revision_id = revision.id
        template.save(update_fields=["current_revision"])


def copy_revisions_back_to_legacy_items(apps, _schema_editor):
    OnboardingTemplate = apps.get_model("lifecycle", "OnboardingTemplate")
    OnboardingTemplateItem = apps.get_model("lifecycle", "OnboardingTemplateItem")
    OnboardingTemplateRevisionItem = apps.get_model(
        "lifecycle",
        "OnboardingTemplateRevisionItem",
    )

    for template in OnboardingTemplate.objects.exclude(current_revision_id=None):
        for item in OnboardingTemplateRevisionItem.objects.filter(
            revision_id=template.current_revision_id,
        ).order_by("id"):
            OnboardingTemplateItem.objects.create(
                template=template,
                app_id=item.app_id,
                authorization_group_id=item.authorization_group_id,
                permission_id=item.permission_id,
                scope_key=item.scope_key,
                grant_type=item.grant_type,
                duration_days=item.duration_days,
            )


def install_template_revision_immutability(_apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                """
                CREATE OR REPLACE FUNCTION lifecycle_reject_template_revision_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Onboarding template revisions are immutable';
                END;
                $$ LANGUAGE plpgsql;
                """,
            )
            for table, suffix in (
                ("lifecycle_onboardingtemplaterevision", "revision"),
                ("lifecycle_onboardingtemplaterevisionitem", "revision_item"),
            ):
                cursor.execute(
                    f"""
                    CREATE TRIGGER lifecycle_template_{suffix}_no_update
                    BEFORE UPDATE ON {table}
                    FOR EACH ROW
                    EXECUTE FUNCTION lifecycle_reject_template_revision_mutation();
                    """,
                )
                cursor.execute(
                    f"""
                    CREATE TRIGGER lifecycle_template_{suffix}_no_delete
                    BEFORE DELETE ON {table}
                    FOR EACH ROW
                    EXECUTE FUNCTION lifecycle_reject_template_revision_mutation();
                    """,
                )
            return
        if vendor == "sqlite":
            cursor.execute(
                """
                CREATE TRIGGER lifecycle_template_revision_no_update
                BEFORE UPDATE ON lifecycle_onboardingtemplaterevision
                BEGIN
                    SELECT RAISE(ABORT, 'OnboardingTemplateRevision is immutable');
                END;
                """,
            )
            cursor.execute(
                """
                CREATE TRIGGER lifecycle_template_revision_no_delete
                BEFORE DELETE ON lifecycle_onboardingtemplaterevision
                BEGIN
                    SELECT RAISE(ABORT, 'OnboardingTemplateRevision is immutable');
                END;
                """,
            )
            cursor.execute(
                """
                CREATE TRIGGER lifecycle_template_revision_item_no_update
                BEFORE UPDATE ON lifecycle_onboardingtemplaterevisionitem
                BEGIN
                    SELECT RAISE(ABORT, 'OnboardingTemplateRevisionItem is immutable');
                END;
                """,
            )
            cursor.execute(
                """
                CREATE TRIGGER lifecycle_template_revision_item_no_delete
                BEFORE DELETE ON lifecycle_onboardingtemplaterevisionitem
                BEGIN
                    SELECT RAISE(ABORT, 'OnboardingTemplateRevisionItem is immutable');
                END;
                """,
            )


def drop_template_revision_immutability(_apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            for table, suffix in (
                ("lifecycle_onboardingtemplaterevision", "revision"),
                ("lifecycle_onboardingtemplaterevisionitem", "revision_item"),
            ):
                cursor.execute(
                    f"DROP TRIGGER IF EXISTS lifecycle_template_{suffix}_no_update ON {table};",
                )
                cursor.execute(
                    f"DROP TRIGGER IF EXISTS lifecycle_template_{suffix}_no_delete ON {table};",
                )
            cursor.execute(
                "DROP FUNCTION IF EXISTS lifecycle_reject_template_revision_mutation();",
            )
            return
        if vendor == "sqlite":
            for trigger_name in (
                "lifecycle_template_revision_no_update",
                "lifecycle_template_revision_no_delete",
                "lifecycle_template_revision_item_no_update",
                "lifecycle_template_revision_item_no_delete",
            ):
                cursor.execute(f"DROP TRIGGER IF EXISTS {trigger_name};")


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_notification_channel_directory_scope'),
        ('lifecycle', '0003_transferplan_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(max_length=128)),
                ('description_snapshot', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='lifecycle.onboardingtemplate')),
            ],
            options={
                'ordering': ['template_id', '-revision'],
            },
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lifecycle.onboardingtemplaterevision'),
        ),
        migrations.AddField(
            model_name='transferplan',
            name='new_template_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_plans', to='lifecycle.onboardingtemplaterevision'),
        ),
        migrations.CreateModel(
            name='OnboardingTemplateRevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(blank=True, max_length=64)),
                ('grant_type', models.CharField(default='permanent', max_length=16)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_template_items', to='applications.app')),
                ('authorization_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_template_items', to='applications.authorizationgroup')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_template_items', to='applications.permission')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lifecycle.onboardingtemplaterevision')),
            ],
            options={
                'ordering': ['revision_id', 'app__app_key', 'id'],
            },
        ),
        migrations.RunPython(
            fail_if_existing_transfer_plans_need_unprovable_revision_binding,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            copy_existing_templates_to_revisions,
            copy_revisions_back_to_legacy_items,
        ),
        migrations.DeleteModel(
            name='OnboardingTemplateItem',
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'revision'), name='lifecycle_template_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplaterevisionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorization_group__isnull', False), ('permission__isnull', True)), models.Q(('authorization_group__isnull', True), ('permission__isnull', False)), _connector='OR'), name='lifecycle_template_revision_item_target_shape'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplaterevisionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_days__isnull', True), ('grant_type', 'permanent')), models.Q(('duration_days__isnull', False), ('grant_type', 'timed')), _connector='OR'), name='lifecycle_template_revision_item_expiration_shape'),
        ),
        migrations.RunPython(
            install_template_revision_immutability,
            drop_template_revision_immutability,
        ),
    ]
