# Generated by Codex on 2026-07-27

from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("lifecycle", "0004_onboardingtemplaterevision_and_more"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AddField(
            model_name="handoverappaction",
            name="preview_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
