# Generated by Django 5.2.15 on 2026-08-10 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_retention_indexes'),
        ('applications', '0031_app_handover_capability'),
        ('lifecycle', '0006_handover_v2_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverappaction',
            name='result_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handovertask',
            name='authority_source',
            field=models.CharField(blank=True, default='manager_chain', max_length=32),
        ),
        migrations.CreateModel(
            name='ApprovalRuleReplacementRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id_snapshot', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_todos', to='applications.approvalrule')),
                ('departed_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_rule_replacement_todos', to='accounts.usermirror')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rule_replacements', to='lifecycle.handovertask')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('approval_rule', 'departed_user'), name='lifecycle_approval_rule_replacement_open_unique')],
            },
        ),
    ]
