# Generated by Django 5.2.15 on 2026-07-26 18:35

from django.db import migrations, models
from django.db.models import Max, Min, Q


def _fail_if_invalid_stream_events(apps, _schema_editor):
    stream_event = apps.get_model("integrations", "DingTalkStreamEvent")
    valid_shape = (
        Q(status__in=("received", "processed", "skipped", "failed"))
        & (
            Q(status="received", processed_at__isnull=True, error="")
            | Q(status__in=("processed", "skipped"), processed_at__isnull=False, error="")
            | Q(status="failed", processed_at__isnull=False, error__gt="")
        )
    )
    invalid = stream_event.objects.exclude(valid_shape)
    invalid_count = invalid.count()
    if invalid_count:
        bounds = invalid.aggregate(min_pk=Min("pk"), max_pk=Max("pk"))
        raise RuntimeError(
            "DingTalkStreamEvent 状态机存在非法历史数据, 已拒绝继续迁移: "
            f"count={invalid_count}, pk_range={bounds['min_pk']}..{bounds['max_pk']}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            _fail_if_invalid_stream_events,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='dingtalkstreamevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('received', 'processed', 'skipped', 'failed'))), name='integrations_stream_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='dingtalkstreamevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('error', ''), ('processed_at__isnull', True), ('status', 'received')), models.Q(('error', ''), ('processed_at__isnull', False), ('status__in', ('processed', 'skipped'))), models.Q(('error__gt', ''), ('processed_at__isnull', False), ('status', 'failed')), _connector='OR'), name='integrations_stream_state_shape'),
        ),
    ]
