# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_dingtalkstreamevent_integrations_stream_status_supported_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dingtalkstreamevent",
            name="data_minimized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dingtalkstreamevent",
            name="data_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="dingtalkstreamevent",
            index=models.Index(
                fields=["status", "data_minimized_at", "processed_at", "id"],
                name="integr_stream_retention_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dingtalkstreamevent",
            index=models.Index(
                fields=["event_type", "-created_at", "-id"],
                name="integr_stream_event_type_idx",
            ),
        ),
    ]
