# Generated by Django 5.2.15 on 2026-06-06 06:30
# ruff: noqa: E501

from collections.abc import Sequence
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0004_role_requestable"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddField(
            model_name="permission",
            name="deprecated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="deprecated_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                ("depth", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permission_groups", to="applications.app")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="applications.permissiongroup")),
            ],
            options={
                "ordering": ["app__app_key", "depth", "display_order", "key"],
            },
        ),
        migrations.AddField(
            model_name="permission",
            name="group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="permissions", to="applications.permissiongroup"),
        ),
        migrations.CreateModel(
            name="PermissionTemplateVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("source", models.CharField(choices=[("upload", "upload"), ("paste", "paste"), ("manual", "manual")], max_length=32)),
                ("content_hash", models.CharField(max_length=64)),
                ("raw_template", models.TextField(blank=True)),
                ("import_summary", models.JSONField(default=dict)),
                ("imported_by", models.CharField(max_length=128)),
                ("imported_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("imported", "imported"), ("rejected", "rejected")], default="imported", max_length=32)),
                ("app", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permission_template_versions", to="applications.app")),
            ],
            options={
                "ordering": ["app__app_key", "-version"],
            },
        ),
        migrations.CreateModel(
            name="AppMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=128)),
                ("role", models.CharField(choices=[("owner", "owner"), ("developer", "developer")], max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="applications.app")),
            ],
            options={
                "ordering": ["app__app_key", "user_id", "role"],
                "constraints": [models.UniqueConstraint(fields=("app", "user_id", "role"), name="applications_app_membership_unique"), models.CheckConstraint(condition=models.Q(("role__in", ("owner", "developer"))), name="applications_app_membership_role_supported")],
            },
        ),
        migrations.AddConstraint(
            model_name="permissiongroup",
            constraint=models.UniqueConstraint(fields=("app", "key"), name="applications_permission_group_app_key_unique"),
        ),
        migrations.AddConstraint(
            model_name="permissiongroup",
            constraint=models.CheckConstraint(condition=models.Q(("depth__gte", 1), ("depth__lte", 5)), name="applications_permission_group_depth_supported"),
        ),
        migrations.AddConstraint(
            model_name="permissiontemplateversion",
            constraint=models.UniqueConstraint(fields=("app", "version"), name="applications_permission_template_version_unique"),
        ),
    ]
