# Generated by Django 5.2.15 on 2026-07-01 04:18

from collections.abc import Sequence
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.operations.base import Operation
from django.db.migrations.state import StateApps
from django.utils import timezone


def migrate_role_catalog(apps: StateApps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    App = apps.get_model("applications", "App")
    AppScope = apps.get_model("applications", "AppScope")
    AuthorizationGroup = apps.get_model("applications", "AuthorizationGroup")
    AuthorizationGroupAccessPolicy = apps.get_model(
        "applications",
        "AuthorizationGroupAccessPolicy",
    )
    AuthorizationGroupGrant = apps.get_model("applications", "AuthorizationGroupGrant")
    Permission = apps.get_model("applications", "Permission")
    Role = apps.get_model("applications", "Role")
    RoleAccessPolicy = apps.get_model("applications", "RoleAccessPolicy")
    RolePermission = apps.get_model("applications", "RolePermission")
    for app in App.objects.all():
        AppScope.objects.get_or_create(
            app_id=app.id,
            key="GLOBAL",
            defaults={
                "name": "Global",
                "description": "Default global scope for migrated permissions.",
                "display_order": 0,
                "is_active": True,
            },
        )

    Permission.objects.all().update(supported_scopes=["GLOBAL"])

    role_group_ids = {}
    for role in Role.objects.all():
        group, _ = AuthorizationGroup.objects.get_or_create(
            app_id=role.app_id,
            key=role.key,
            defaults={
                "kind": "role",
                "name": role.name,
                "description": role.description,
                "requestable": role.requestable,
                "is_active": role.is_active,
                "created_at": role.created_at or timezone.now(),
                "updated_at": role.updated_at or timezone.now(),
            },
        )
        role_group_ids[role.id] = group.id

    for role_permission in RolePermission.objects.all():
        group_id = role_group_ids.get(role_permission.role_id)
        if group_id is None:
            continue
        AuthorizationGroupGrant.objects.get_or_create(
            authorization_group_id=group_id,
            permission_id=role_permission.permission_id,
            scope_key="GLOBAL",
            defaults={"is_active": True},
        )

    for role_policy in RoleAccessPolicy.objects.all():
        group_id = role_group_ids.get(role_policy.role_id)
        if group_id is None:
            continue
        AuthorizationGroupAccessPolicy.objects.get_or_create(
            authorization_group_id=group_id,
            defaults={
                "is_high_risk": role_policy.is_high_risk,
                "max_grant_duration_days": role_policy.max_grant_duration_days,
            },
        )


class Migration(migrations.Migration):

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0008_authentik_directory_health_dependency"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name="AppScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["app__app_key", "display_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("requestable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["app__app_key", "kind", "key"],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationGroupGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_key", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "authorization_group__app__app_key",
                    "authorization_group__key",
                    "permission__key",
                    "scope_key",
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationGroupAccessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_high_risk", models.BooleanField(default=False)),
                ("max_grant_duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "authorization_group__app__app_key",
                    "authorization_group__key",
                ],
            },
        ),
        migrations.AddField(
            model_name="app",
            name="catalog_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="permission",
            name="risk_level",
            field=models.CharField(default="standard", max_length=32),
        ),
        migrations.AddField(
            model_name="permission",
            name="supported_scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.CheckConstraint(
                condition=models.Q(("risk_level__in", ("standard", "high"))),
                name="applications_permission_risk_level_supported",
            ),
        ),
        migrations.AddField(
            model_name="appscope",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="applications.app",
            ),
        ),
        migrations.AddField(
            model_name="authorizationgroup",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorization_groups",
                to="applications.app",
            ),
        ),
        migrations.AddField(
            model_name="authorizationgroupgrant",
            name="authorization_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="applications.authorizationgroup",
            ),
        ),
        migrations.AddField(
            model_name="authorizationgroupgrant",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorization_group_grants",
                to="applications.permission",
            ),
        ),
        migrations.AddField(
            model_name="authorizationgroupaccesspolicy",
            name="authorization_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_policies",
                to="applications.authorizationgroup",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="authorization_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_rules",
                to="applications.authorizationgroup",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="approvalrule",
            name="applications_approval_rule_one_target",
        ),
        migrations.AddConstraint(
            model_name="appscope",
            constraint=models.UniqueConstraint(
                fields=("app", "key"),
                name="applications_app_scope_app_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizationgroup",
            constraint=models.UniqueConstraint(
                fields=("app", "key"),
                name="applications_authorization_group_app_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizationgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("role", "bundle"))),
                name="applications_authorization_group_kind_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizationgroupgrant",
            constraint=models.UniqueConstraint(
                fields=("authorization_group", "permission", "scope_key"),
                name="applications_authorization_group_grant_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizationgroupaccesspolicy",
            constraint=models.UniqueConstraint(
                fields=("authorization_group",),
                name="applications_authorization_group_access_policy_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizationgroupaccesspolicy",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("max_grant_duration_days__isnull", True))
                    | models.Q(("max_grant_duration_days__gte", 1))
                ),
                name="applications_authorization_group_access_policy_max_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizationgroupaccesspolicy",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("is_high_risk", True),
                        ("max_grant_duration_days__isnull", False),
                    )
                    | models.Q(
                        ("is_high_risk", False),
                        ("max_grant_duration_days__isnull", True),
                    )
                ),
                name="applications_authorization_group_access_policy_high_risk_shape",
            ),
        ),
        migrations.RunPython(migrate_role_catalog, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="approvalrule",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        role__isnull=True,
                        authorization_group__isnull=False,
                        permission__isnull=True,
                    )
                    | models.Q(
                        role__isnull=True,
                        authorization_group__isnull=True,
                        permission__isnull=False,
                    )
                ),
                name="applications_approval_rule_one_target",
            ),
        ),
    ]
