# Generated by Django 5.2.15 on 2026-07-02 10:40

from collections.abc import Sequence
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0009_atomic_authorization_models"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name="ManagedScopePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.PositiveBigIntegerField()),
                ("scope", models.CharField(max_length=64)),
                ("resolver", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_scope_policies",
                        to="applications.app",
                    ),
                ),
            ],
            options={
                "ordering": ["app__app_key", "target_type", "target_id", "scope"],
            },
        ),
        migrations.AddConstraint(
            model_name="managedscopepolicy",
            constraint=models.UniqueConstraint(
                fields=("app", "target_type", "target_id", "scope"),
                name="applications_managed_scope_policy_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedscopepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_type__in",
                        ("app_default", "authorization_group_grant"),
                    ),
                ),
                name="applications_managed_scope_policy_target_type_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedscopepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope", "MANAGED_USERS")),
                name="applications_managed_scope_policy_scope_managed_users",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedscopepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "resolver__in",
                        ("dingtalk_manager_chain", "disabled"),
                    ),
                ),
                name="applications_managed_scope_policy_resolver_supported",
            ),
        ),
    ]
