# Generated by Django 5.2.15 on 2026-07-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_managed_scope_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="token_lookup",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
