# Generated by Django 5.2.15 on 2026-07-03 12:59

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0012_approval_rule_target_unique"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddField(
            model_name="appscope",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appscope",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="authorizationgroup",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="authorizationgroup",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="permission",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="permission",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
