# Generated by Django 5.2.15 on 2026-07-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_catalog_bilingual_display_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentik_base_url', models.CharField(blank=True, max_length=512)),
                ('authentik_api_token', models.CharField(blank=True, max_length=512)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='applications_integration_settings_singleton')],
            },
        ),
    ]
