# Generated by Django 5.2.15 on 2026-07-05 12:39

import easyauth.config.crypto
from django.db import migrations


def _blank_plaintext_token(apps, schema_editor):
    # 项目尚未上线: 历史明文 Authentik 管理 token 无法被重新加密, 必须清空并按
    # "部署后重新录入" runbook 处理, 避免留下无法解密的密文。
    _ = schema_editor
    integration_settings = apps.get_model("applications", "IntegrationSettings")
    _ = integration_settings.objects.update(authentik_api_token="")


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_integrationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='authentik_api_token',
            field=easyauth.config.crypto.EncryptedCharField(blank=True, max_length=1024),
        ),
        migrations.RunPython(_blank_plaintext_token, migrations.RunPython.noop, elidable=True),
    ]
