from __future__ import annotations

# Generated by Django 5.2.15 on 2026-07-05 12:39
from typing import TYPE_CHECKING, ClassVar, Protocol, cast

from django.db import migrations

import easyauth.config.crypto

if TYPE_CHECKING:
    from collections.abc import Sequence

    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.operations.base import Operation


class _MigrationQuerySet(Protocol):
    def order_by(self, *field_names: str) -> _MigrationQuerySet: ...

    def count(self) -> int: ...

    def values_list(self, field_name: str, *, flat: bool = False) -> Sequence[int]: ...


class _MigrationManager(Protocol):
    def exclude(self, **kwargs: object) -> _MigrationQuerySet: ...


class _HistoricalIntegrationSettings(Protocol):
    objects: _MigrationManager


def _assert_no_plaintext_token(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    _ = schema_editor
    integration_settings = cast(
        "_HistoricalIntegrationSettings",
        apps.get_model("applications", "IntegrationSettings"),
    )
    queryset = integration_settings.objects.exclude(authentik_api_token="").order_by("id")
    count = queryset.count()
    if count:
        sample_ids = list(queryset.values_list("id", flat=True)[:5])
        message = (
            "EA-AUD-023 迁移被阻断: applications.0015 不能清空已有 Authentik 管理 "
            "token 或把明文当作新密文继续使用。"
            f" count={count}, sample_ids={sample_ids}。请先通过显式运维流程重新录入凭据。"
        )
        raise RuntimeError(message)


class Migration(migrations.Migration):

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0014_integrationsettings"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.RunPython(_assert_no_plaintext_token, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="integrationsettings",
            name="authentik_api_token",
            field=easyauth.config.crypto.EncryptedCharField(blank=True, max_length=1024),
        ),
    ]
