# Generated by Django 5.2.15 on 2026-07-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_integrationsettings_authentik_api_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authorizationgroupaccesspolicy',
            name='applications_authorization_group_access_policy_max_duration_positive',
        ),
        migrations.RemoveConstraint(
            model_name='authorizationgroupaccesspolicy',
            name='applications_authorization_group_access_policy_high_risk_shape',
        ),
        migrations.RemoveConstraint(
            model_name='roleaccesspolicy',
            name='applications_role_access_policy_max_duration_positive',
        ),
        migrations.RemoveConstraint(
            model_name='roleaccesspolicy',
            name='applications_role_access_policy_high_risk_shape',
        ),
        migrations.RemoveField(
            model_name='authorizationgroupaccesspolicy',
            name='is_high_risk',
        ),
        migrations.RemoveField(
            model_name='authorizationgroupaccesspolicy',
            name='max_grant_duration_days',
        ),
        migrations.RemoveField(
            model_name='roleaccesspolicy',
            name='is_high_risk',
        ),
        migrations.RemoveField(
            model_name='roleaccesspolicy',
            name='max_grant_duration_days',
        ),
    ]
