# Generated by Django 5.2.15 on 2026-07-06 04:49

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('applications', '0017_assert_static_credential_token_lookup'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.RemoveConstraint(
            model_name='managedscopepolicy',
            name='applications_managed_scope_policy_resolver_supported',
        ),
        migrations.AddConstraint(
            model_name='managedscopepolicy',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'resolver__in',
                        ('dingtalk_manager_chain', 'easyauth_team', 'union', 'disabled'),
                    ),
                ),
                name='applications_managed_scope_policy_resolver_supported',
            ),
        ),
    ]
