# Generated by Django 5.2.15 on 2026-07-06 05:19

import easyauth.config.crypto
from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('applications', '0018_remove_managedscopepolicy_applications_managed_scope_policy_resolver_supported_and_more'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddField(
            model_name='integrationsettings',
            name='dingtalk_agent_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='dingtalk_app_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='dingtalk_app_secret',
            field=easyauth.config.crypto.EncryptedCharField(blank=True, max_length=1024),
        ),
    ]
