# Generated by Django 5.2.16 on 2026-07-07 14:40

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('applications', '0019_integrationsettings_dingtalk_agent_id_and_more'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.RemoveConstraint(
            model_name='dependencyhealthsnapshot',
            name='applications_dependency_health_dependency_supported',
        ),
        migrations.AlterField(
            model_name='dependencyhealthsnapshot',
            name='dependency',
            field=models.CharField(choices=[('authentik', 'authentik'), ('authentik_directory', 'authentik_directory'), ('dingtalk', 'dingtalk'), ('celery', 'celery'), ('connectors', 'connectors')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='dependencyhealthsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('dependency__in', ('authentik', 'authentik_directory', 'dingtalk', 'celery', 'connectors'))), name='applications_dependency_health_dependency_supported'),
        ),
    ]
