# Generated by Django 5.2.16 on 2026-07-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_delete_legacy_role_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('directory', 'directory'), ('notify', 'notify')], max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_capabilities', to='applications.app')),
            ],
            options={
                'ordering': ['app__app_key', 'capability'],
                'constraints': [models.UniqueConstraint(fields=('app', 'capability'), name='applications_app_capability_unique')],
            },
        ),
    ]
