# Generated by Django 5.2.16 on 2026-07-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_app_capability_and_directory_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dependencyhealthsnapshot',
            name='applications_dependency_health_dependency_supported',
        ),
        migrations.AlterField(
            model_name='dependencyhealthsnapshot',
            name='dependency',
            field=models.CharField(choices=[('authentik', 'authentik'), ('authentik_directory', 'authentik_directory'), ('dingtalk', 'dingtalk'), ('dingtalk_notify', 'dingtalk_notify'), ('celery', 'celery'), ('connectors', 'connectors')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='dependencyhealthsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('dependency__in', ('authentik', 'authentik_directory', 'dingtalk', 'dingtalk_notify', 'celery', 'connectors'))), name='applications_dependency_health_dependency_supported'),
        ),
    ]
