from __future__ import annotations

# Generated by Django 5.2.15 on 2026-07-16 14:11
from typing import TYPE_CHECKING, ClassVar, Protocol, cast

from django.db import migrations, models

import easyauth.applications.credential_capabilities

if TYPE_CHECKING:
    from collections.abc import Sequence

    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.operations.base import Operation


class _MigrationQuerySet(Protocol):
    def count(self) -> int: ...

    def values_list(self, field_name: str, *, flat: bool = False) -> Sequence[int]: ...


class _FilteredQuerySet(_MigrationQuerySet, Protocol):
    def filter(self, **kwargs: object) -> _FilteredQuerySet: ...


class _MigrationManager(Protocol):
    def filter(self, **kwargs: object) -> _FilteredQuerySet: ...


class _HistoricalModel(Protocol):
    objects: _MigrationManager


def assert_no_credential_capability_backfill_targets(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    _ = schema_editor
    app_capability = cast(
        "_HistoricalModel",
        apps.get_model("applications", "AppCapability"),
    )
    app_credential = cast(
        "_HistoricalModel",
        apps.get_model("applications", "AppCredential"),
    )
    oauth_binding = cast(
        "_HistoricalModel",
        apps.get_model("applications", "OAuthClientBinding"),
    )
    enabled_app_ids = list(
        app_capability.objects.filter(enabled=True).values_list("app_id", flat=True),
    )
    if not enabled_app_ids:
        return
    credential_count = app_credential.objects.filter(
        app_id__in=enabled_app_ids,
        is_active=True,
    ).count()
    oauth_binding_count = oauth_binding.objects.filter(
        app_id__in=enabled_app_ids,
        is_active=True,
    ).count()
    if credential_count or oauth_binding_count:
        sample_app_ids = sorted(set(enabled_app_ids))[:5]
        message = (
            "EA-AUD-023 迁移被阻断: applications.0025 不能把 App capability "
            "静默授权给 active credential。"
            f" credential_count={credential_count}, oauth_binding_count={oauth_binding_count}, "
            f"sample_app_ids={sample_app_ids}。请先由 App owner 显式授予单凭据 capability。"
        )
        raise RuntimeError(message)


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        (
            "applications",
            "0024_remove_dependencyhealthsnapshot_applications_dependency_health_dependency_supported_and_more",
        ),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.RunPython(
            assert_no_credential_capability_backfill_targets,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="appcredential",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[
                    easyauth.applications.credential_capabilities.validate_credential_capabilities
                ],
            ),
        ),
        migrations.AddField(
            model_name="oauthclientbinding",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[
                    easyauth.applications.credential_capabilities.validate_credential_capabilities
                ],
            ),
        ),
    ]
