# Generated by Django 5.2.15 on 2026-07-16 14:11

import easyauth.applications.credential_capabilities
from django.db import migrations, models


def backfill_enabled_capabilities(apps, schema_editor):
    app_capability = apps.get_model("applications", "AppCapability")
    app_credential = apps.get_model("applications", "AppCredential")
    oauth_binding = apps.get_model("applications", "OAuthClientBinding")
    enabled_rows = app_capability.objects.filter(enabled=True).values_list(
        "app_id",
        "capability",
    )
    by_app = {}
    for app_id, capability in enabled_rows:
        by_app.setdefault(app_id, []).append(capability)
    for app_id, capabilities in by_app.items():
        normalized = sorted(set(capabilities))
        app_credential.objects.filter(app_id=app_id, is_active=True).update(
            capabilities=normalized,
        )
        oauth_binding.objects.filter(app_id=app_id, is_active=True).update(
            capabilities=normalized,
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0024_remove_dependencyhealthsnapshot_applications_dependency_health_dependency_supported_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[
                    easyauth.applications.credential_capabilities.validate_credential_capabilities
                ],
            ),
        ),
        migrations.AddField(
            model_name="oauthclientbinding",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[
                    easyauth.applications.credential_capabilities.validate_credential_capabilities
                ],
            ),
        ),
        migrations.RunPython(backfill_enabled_capabilities, migrations.RunPython.noop),
    ]
