# Generated by Django 5.2.15 on 2026-07-16 14:15

import django.db.models.deletion
import easyauth.config.crypto
from django.db import migrations, models


def copy_global_channel_to_notify_apps(apps, schema_editor):
    integration_settings = apps.get_model("applications", "IntegrationSettings")
    app_capability = apps.get_model("applications", "AppCapability")
    channel = apps.get_model("applications", "AppNotificationChannel")
    settings_row = integration_settings.objects.filter(pk=1).first()
    if settings_row is None:
        return
    app_key = settings_row.dingtalk_app_key.strip()
    app_secret = settings_row.dingtalk_app_secret.strip()
    agent_id = settings_row.dingtalk_agent_id.strip()
    if not app_key or not app_secret or not agent_id:
        return
    app_ids = app_capability.objects.filter(
        capability="notify",
        enabled=True,
    ).values_list("app_id", flat=True)
    for app_id in app_ids:
        channel.objects.create(
            app_id=app_id,
            name="迁移自全局钉钉通知配置",
            dingtalk_app_key=app_key,
            dingtalk_app_secret=app_secret,
            agent_id=agent_id,
            version=1,
            is_active=True,
            created_by="migration",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0025_credential_capabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppNotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("dingtalk_app_key", models.CharField(max_length=128)),
                ("dingtalk_app_secret", easyauth.config.crypto.EncryptedCharField(max_length=1024)),
                ("agent_id", models.CharField(max_length=64)),
                ("version", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to="applications.app",
                    ),
                ),
            ],
            options={
                "ordering": ["app__app_key", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app", "version"),
                        name="applications_notify_channel_app_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("app",),
                        name="applications_notify_channel_one_active",
                    ),
                ],
            },
        ),
        migrations.RunPython(copy_global_channel_to_notify_apps, migrations.RunPython.noop),
    ]
