# Generated by Django 5.2.15 on 2026-07-16 14:15

from collections.abc import Iterator, Sequence
from typing import ClassVar, Protocol, Self, cast

from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.operations.base import Operation

import easyauth.config.crypto


class _HistoricalQuery(Protocol):
    def __iter__(self) -> Iterator[object]: ...
    def filter(self, **kwargs: object) -> Self: ...
    def values_list(self, *fields: str, flat: bool = False) -> Self: ...


class _IntegrationSettingsRow(Protocol):
    dingtalk_app_key: str
    dingtalk_app_secret: str
    dingtalk_agent_id: str


class _IntegrationSettingsQuery(_HistoricalQuery, Protocol):
    def first(self) -> _IntegrationSettingsRow | None: ...


class _IntegrationSettingsManager(Protocol):
    def filter(self, **kwargs: object) -> _IntegrationSettingsQuery: ...


class _IntegrationSettingsModel(Protocol):
    objects: ClassVar[_IntegrationSettingsManager]


class _AppCapabilityModel(Protocol):
    objects: ClassVar[_HistoricalQuery]


class _ChannelManager(Protocol):
    def create(self, **kwargs: object) -> object: ...


class _ChannelModel(Protocol):
    objects: ClassVar[_ChannelManager]


def copy_global_channel_to_notify_apps(
    apps: Apps,
    _schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    integration_settings = cast(
        "type[_IntegrationSettingsModel]",
        cast("object", apps.get_model("applications", "IntegrationSettings")),
    )
    app_capability = cast(
        "type[_AppCapabilityModel]",
        cast("object", apps.get_model("applications", "AppCapability")),
    )
    channel = cast(
        "type[_ChannelModel]",
        cast("object", apps.get_model("applications", "AppNotificationChannel")),
    )
    settings_row = integration_settings.objects.filter(pk=1).first()
    override_app_key = settings_row.dingtalk_app_key.strip() if settings_row is not None else ""
    override_app_secret = (
        settings_row.dingtalk_app_secret.strip() if settings_row is not None else ""
    )
    override_agent_id = settings_row.dingtalk_agent_id.strip() if settings_row is not None else ""
    app_key = override_app_key or str(getattr(settings, "EASYAUTH_DINGTALK_APP_KEY", "")).strip()
    app_secret = (
        override_app_secret
        or str(
            getattr(settings, "EASYAUTH_DINGTALK_APP_SECRET", ""),
        ).strip()
    )
    agent_id = (
        override_agent_id
        or str(
            getattr(settings, "EASYAUTH_DINGTALK_AGENT_ID", ""),
        ).strip()
    )
    if not app_key or not app_secret or not agent_id:
        return
    app_ids = cast(
        "list[int]",
        list(
            app_capability.objects.filter(
                capability="notify",
                enabled=True,
            ).values_list("app_id", flat=True),
        ),
    )
    for app_id in app_ids:
        _ = channel.objects.create(
            app_id=app_id,
            name="迁移自全局钉钉通知配置",
            dingtalk_app_key=app_key,
            dingtalk_app_secret=app_secret,
            agent_id=agent_id,
            version=1,
            is_active=True,
            created_by="migration",
        )


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0025_credential_capabilities"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name="AppNotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("dingtalk_app_key", models.CharField(max_length=128)),
                ("dingtalk_app_secret", easyauth.config.crypto.EncryptedCharField(max_length=1024)),
                ("agent_id", models.CharField(max_length=64)),
                ("version", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="notification_channels",
                        to="applications.app",
                    ),
                ),
            ],
            options={
                "ordering": ["app__app_key", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app", "version"),
                        name="applications_notify_channel_app_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("app",),
                        name="applications_notify_channel_one_active",
                    ),
                ],
            },
        ),
        migrations.RunPython(copy_global_channel_to_notify_apps, migrations.RunPython.noop),
    ]
