# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0029_managed_scope_policy_relationship_triggers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dependencyhealthsnapshot",
            index=models.Index(
                fields=["checked_at", "id"],
                name="app_dep_health_retention_idx",
            ),
        ),
    ]
