# Generated by Django 5.2.15 on 2026-08-11 02:01

import easyauth.config.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_app_handover_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='descriptor_base_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='app',
            name='descriptor_token',
            field=easyauth.config.crypto.EncryptedCharField(blank=True, max_length=1024),
        ),
    ]
