# Generated by Django 5.2.15 on 2026-07-06 05:19

import django.db.models.deletion
import uuid
from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial: ClassVar[bool | None] = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('accounts', '0008_localadminaccount_totp_last_timestep'),
        ('applications', '0019_integrationsettings_dingtalk_agent_id_and_more'),
        ('webhooks', '0001_initial'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('dingtalk_process_code', models.CharField(max_length=128)),
                ('form_schema', models.JSONField(blank=True, default=dict)),
                ('form_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_templates', to='applications.app')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biz_key', models.CharField(max_length=128)),
                ('dingtalk_process_instance_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('created', 'created'), ('submitted', 'submitted'), ('approved', 'approved'), ('rejected', 'rejected'), ('canceled', 'canceled'), ('failed', 'failed')], default='created', max_length=16)),
                ('form_values', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='applications.app')),
                ('completion_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_instances', to='webhooks.webhookdelivery')),
                ('originator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_approval_instances', to='accounts.usermirror')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.approvaltemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvaltemplate',
            constraint=models.UniqueConstraint(fields=('app', 'key'), name='workflows_template_key_unique_per_app'),
        ),
        migrations.AddConstraint(
            model_name='approvaltemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('app__isnull', True)), fields=('key',), name='workflows_template_key_unique_platform'),
        ),
        migrations.AddConstraint(
            model_name='approvalinstance',
            constraint=models.UniqueConstraint(fields=('app', 'template', 'biz_key'), name='workflows_instance_biz_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='approvalinstance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('created', 'submitted', 'approved', 'rejected', 'canceled', 'failed'))), name='workflows_instance_status_supported'),
        ),
    ]
