# Generated by Django 5.2.15 on 2026-07-26 18:35

from django.db import migrations, models
from django.db.models import Max, Min, Q


def _fail_if_invalid_pending_callbacks(apps, _schema_editor):
    pending_callback = apps.get_model("workflows", "PendingApprovalCallback")
    valid_shape = (
        Q(status__in=("approved", "rejected", "canceled"))
        & Q(state__in=("pending", "applied", "conflict"))
        & (
            Q(
                state="pending",
                instance__isnull=True,
                applied_at__isnull=True,
                last_error="",
            )
            | Q(
                state="applied",
                instance__isnull=False,
                applied_at__isnull=False,
                last_error="",
            )
            | Q(
                state="conflict",
                applied_at__isnull=True,
                last_error__gt="",
            )
        )
    )
    invalid = pending_callback.objects.exclude(valid_shape)
    invalid_count = invalid.count()
    if invalid_count:
        bounds = invalid.aggregate(min_pk=Min("pk"), max_pk=Max("pk"))
        raise RuntimeError(
            "PendingApprovalCallback 状态机存在非法历史数据, 已拒绝继续迁移: "
            f"count={invalid_count}, pk_range={bounds['min_pk']}..{bounds['max_pk']}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_submission_contract_and_pending_callbacks'),
    ]

    operations = [
        migrations.RunPython(
            _fail_if_invalid_pending_callbacks,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='pendingapprovalcallback',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('approved', 'rejected', 'canceled'))), name='workflows_callback_status_terminal'),
        ),
        migrations.AddConstraint(
            model_name='pendingapprovalcallback',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('pending', 'applied', 'conflict'))), name='workflows_callback_state_supported'),
        ),
        migrations.AddConstraint(
            model_name='pendingapprovalcallback',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', True), ('instance__isnull', True), ('last_error', ''), ('state', 'pending')), models.Q(('applied_at__isnull', False), ('instance__isnull', False), ('last_error', ''), ('state', 'applied')), models.Q(('applied_at__isnull', True), ('last_error__gt', ''), ('state', 'conflict')), _connector='OR'), name='workflows_callback_state_shape'),
        ),
    ]
