# Generated by Django 5.2.16 on 2026-07-07 14:40

import django.db.models.deletion
import easyauth.config.crypto
from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial: ClassVar[bool | None] = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('applications', '0020_remove_dependencyhealthsnapshot_applications_dependency_health_dependency_supported_and_more'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name='ConnectorInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_key', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('config_encrypted', easyauth.config.crypto.EncryptedTextField(blank=True, default='')),
                ('reconcile_interval_seconds', models.PositiveIntegerField(default=300)),
                ('last_reconcile_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_instances', to='applications.app')),
            ],
            options={
                'ordering': ['app__app_key', 'connector_key'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(max_length=255)),
                ('auto_create', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_mappings', to='applications.authorizationgroup')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='connectors.connectorinstance')),
            ],
            options={
                'ordering': ['instance_id', 'authorization_group__key'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('periodic', 'periodic'), ('event', 'event'), ('manual', 'manual'), ('offboard', 'offboard')], max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', 'success'), ('partial', 'partial'), ('failed', 'failed')], max_length=16)),
                ('stats', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='connectors.connectorinstance')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='connectorinstance',
            constraint=models.UniqueConstraint(fields=('app', 'connector_key'), name='connectors_instance_app_connector_unique'),
        ),
        migrations.AddConstraint(
            model_name='connectormapping',
            constraint=models.UniqueConstraint(fields=('instance', 'authorization_group'), name='connectors_mapping_instance_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='connectorsyncrun',
            constraint=models.CheckConstraint(condition=models.Q(('trigger__in', ('periodic', 'event', 'manual', 'offboard'))), name='connectors_sync_run_trigger_supported'),
        ),
        migrations.AddConstraint(
            model_name='connectorsyncrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('success', 'partial', 'failed'))), name='connectors_sync_run_status_supported'),
        ),
    ]
