# Generated by Django 5.2.16 on 2026-07-10

import django.db.models.deletion
from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("connectors", "0001_initial"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddField(
            model_name="connectorinstance",
            name="external_account_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconcile_dirty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconcile_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconcile_lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconcile_lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconcile_pending_trigger",
            field=models.CharField(
                choices=[
                    ("periodic", "periodic"),
                    ("event", "event"),
                    ("manual", "manual"),
                    ("offboard", "offboard"),
                ],
                default="periodic",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconcile_worker_queued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconcile_worker_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="reconciled_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="tombstoned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connectormapping",
            name="external_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="connectormapping",
            name="tombstoned",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name="connectormapping",
            name="connectors_mapping_instance_group_unique",
        ),
        migrations.AlterField(
            model_name="connectormapping",
            name="authorization_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connector_mappings",
                to="applications.authorizationgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectorinstance",
            constraint=models.UniqueConstraint(
                condition=~models.Q(external_account_id=""),
                fields=("connector_key", "external_account_id"),
                name="connectors_instance_external_account_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectormapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(authorization_group__isnull=False, tombstoned=False),
                fields=("instance", "authorization_group"),
                name="connectors_mapping_instance_group_unique",
            ),
        ),
    ]
