# Generated by Django 5.2.16 on 2026-07-27

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("connectors", "0002_reconcile_state_and_external_identity"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddConstraint(
            model_name="connectorinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reconciled_generation__lte", models.F("reconcile_generation")),
                ),
                name="connectors_instance_generation_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectorinstance",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        reconcile_lease_token__isnull=True,
                        reconcile_lease_expires_at__isnull=True,
                    )
                    | models.Q(
                        reconcile_lease_token__isnull=False,
                        reconcile_lease_expires_at__isnull=False,
                    )
                ),
                name="connectors_instance_lease_pair",
            ),
        ),
    ]
