# Generated by Django 5.2.15 on 2026-07-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_external_group_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorinstance',
            name='external_groups_refresh_cursor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='connectorinstance',
            name='external_groups_refresh_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='connectorinstance',
            name='external_groups_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
