# Generated by Django 5.2.15 on 2026-07-06 04:49

from collections.abc import Sequence
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial: ClassVar[bool | None] = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('accounts', '0008_localadminaccount_totp_last_timestep'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'leader'), ('member', 'member')], default='member', max_length=16)),
                ('added_by', models.CharField(blank=True, max_length=128)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='accounts.usermirror')),
            ],
            options={
                'ordering': ['team__name', 'role', 'user__authentik_user_id'],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='teams_team_member_unique'), models.CheckConstraint(condition=models.Q(('role__in', ('leader', 'member'))), name='teams_team_member_role_supported')],
            },
        ),
    ]
