# Generated by Django 5.2.15 on 2026-07-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usermirror_options_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to='accounts.usermirror'),
        ),
    ]
