# Generated by Django 5.2.16 on 2026-09-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField()),
                ('source', models.CharField(choices=[('easyauth', 'easyauth'), ('authentik', 'authentik')], max_length=16)),
                ('category', models.CharField(max_length=64)),
                ('metric', models.CharField(choices=[('api', 'api'), ('webhook', 'webhook'), ('stream', 'stream'), ('internal', 'internal')], max_length=16)),
                ('billed', models.BooleanField()),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('blocked_count', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hour_start', 'source', 'category'],
                'indexes': [
                    models.Index(fields=['hour_start'], name='usage_bucket_hour_idx'),
                    models.Index(fields=['metric', 'hour_start'], name='usage_bucket_metric_hour_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('hour_start', 'source', 'category'), name='usage_bucket_hour_source_cat_uniq'),
                    models.CheckConstraint(condition=models.Q(('source__in', ('easyauth', 'authentik'))), name='usage_bucket_source_supported'),
                    models.CheckConstraint(condition=models.Q(('metric__in', ('api', 'webhook', 'stream', 'internal'))), name='usage_bucket_metric_supported'),
                    models.CheckConstraint(condition=models.Q(('category__in', ('token', 'probe', 'notify_send', 'robot_send', 'notify_reconcile', 'approval', 'stream_open', 'webhook_callback', 'stream_event', 'internal_authentik_directory', 'internal_authentik_admin', 'internal_authentik_other', 'internal_netbird', 'internal_business_webhook', 'internal_business_hook', 'ak_token', 'ak_login', 'ak_auth_info', 'ak_directory_incremental', 'ak_directory_full', 'ak_allowlist'))), name='usage_bucket_category_supported'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UsageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('id', 1)), name='usage_settings_singleton'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UsageRuntimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('stream_paused', models.BooleanField(default=False)),
                ('stream_paused_at', models.DateTimeField(blank=True, null=True)),
                ('stream_paused_period', models.CharField(blank=True, max_length=32)),
                ('stream_manual_resume_period', models.CharField(blank=True, max_length=32)),
                ('authentik_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('authentik_policy_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('authentik_error', models.TextField(blank=True)),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('id', 1)), name='usage_runtime_state_singleton'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UsageAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('threshold', 'threshold'), ('anomaly', 'anomaly'), ('enforcement', 'enforcement'), ('stream_paused', 'stream_paused'), ('stream_resumed', 'stream_resumed')], max_length=32)),
                ('metric', models.CharField(choices=[('api', 'api'), ('webhook', 'webhook'), ('stream', 'stream'), ('internal', 'internal')], max_length=16)),
                ('scope', models.CharField(choices=[('day', 'day'), ('month', 'month'), ('hour', 'hour')], max_length=16)),
                ('period_key', models.CharField(max_length=32)),
                ('threshold_percent', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('suppressed', 'suppressed'), ('superseded', 'superseded'), ('failed', 'failed')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['created_at', 'id'], name='usage_alert_retention_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('kind', 'metric', 'scope', 'period_key', 'threshold_percent'), name='usage_alert_event_dedupe'),
                    models.CheckConstraint(condition=models.Q(('kind__in', ('threshold', 'anomaly', 'enforcement', 'stream_paused', 'stream_resumed'))), name='usage_alert_kind_supported'),
                    models.CheckConstraint(condition=models.Q(('metric__in', ('api', 'webhook', 'stream', 'internal'))), name='usage_alert_metric_supported'),
                    models.CheckConstraint(condition=models.Q(('scope__in', ('day', 'month', 'hour'))), name='usage_alert_scope_supported'),
                    models.CheckConstraint(condition=models.Q(('status__in', ('sent', 'suppressed', 'superseded', 'failed'))), name='usage_alert_status_supported'),
                ],
            },
        ),
    ]
