# Generated by Django 5.2.16 on 2026-09-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagealertevent",
            name="delivery_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usagealertevent",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UsageAlertSendBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_key", models.CharField(max_length=10)),
                ("batch_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["day_key", "batch_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day_key", "batch_key"),
                        name="usage_alert_send_batch_uniq",
                    ),
                ],
            },
        ),
    ]
