"""定义应用目录, 权限, managed scope 与交接能力共享常量。"""

from __future__ import annotations

import re
from typing import Final

from easyauth.applications.credential_capabilities import (
    CAPABILITY_DIRECTORY,
    CAPABILITY_NOTIFY,
)

type JsonValue = None | bool | int | float | str | list[JsonValue] | dict[str, JsonValue]

APP_SCOPE_KEY_PATTERN = re.compile(r"^[A-Z0-9_]+$")

AUTHORIZATION_GROUP_KINDS = ("role", "bundle")
PERMISSION_RISK_LEVELS = ("standard", "high")
MANAGED_SCOPE_POLICY_TARGET_APP_DEFAULT = "app_default"
MANAGED_SCOPE_POLICY_TARGET_AUTHORIZATION_GROUP_GRANT = "authorization_group_grant"
MANAGED_SCOPE_POLICY_TARGET_TYPES = (
    MANAGED_SCOPE_POLICY_TARGET_APP_DEFAULT,
    MANAGED_SCOPE_POLICY_TARGET_AUTHORIZATION_GROUP_GRANT,
)
MANAGED_SCOPE_POLICY_SCOPE_MANAGED_USERS = "MANAGED_USERS"
MANAGED_SCOPE_POLICY_RESOLVER_DINGTALK_MANAGER_CHAIN = "dingtalk_manager_chain"
MANAGED_SCOPE_POLICY_RESOLVER_EASYAUTH_TEAM = "easyauth_team"
MANAGED_SCOPE_POLICY_RESOLVER_UNION = "union"
MANAGED_SCOPE_POLICY_RESOLVER_DISABLED = "disabled"
MANAGED_SCOPE_POLICY_RESOLVERS = (
    MANAGED_SCOPE_POLICY_RESOLVER_DINGTALK_MANAGER_CHAIN,
    MANAGED_SCOPE_POLICY_RESOLVER_EASYAUTH_TEAM,
    MANAGED_SCOPE_POLICY_RESOLVER_UNION,
    MANAGED_SCOPE_POLICY_RESOLVER_DISABLED,
)
# 有效(非 disabled)的 resolver 集合, 供策略写入口与解析入口共用。
MANAGED_SCOPE_POLICY_ACTIVE_RESOLVERS = (
    MANAGED_SCOPE_POLICY_RESOLVER_DINGTALK_MANAGER_CHAIN,
    MANAGED_SCOPE_POLICY_RESOLVER_EASYAUTH_TEAM,
    MANAGED_SCOPE_POLICY_RESOLVER_UNION,
)

# App 维度平台能力(目录/通知); 默认关闭, 由超管在 console 显式开通。
CAPABILITY_CHOICES: Final[tuple[tuple[str, str], ...]] = (
    (CAPABILITY_DIRECTORY, "directory"),
    (CAPABILITY_NOTIFY, "notify"),
)

# 交接能力三态(契约 §9)。
HANDOVER_CAPABILITY_DECLARED: Final = "declared"
HANDOVER_CAPABILITY_NONE: Final = "none"
HANDOVER_CAPABILITY_UNDECLARED: Final = "undeclared"
HANDOVER_CAPABILITY_CHOICES: Final[tuple[tuple[str, str], ...]] = (
    (HANDOVER_CAPABILITY_DECLARED, "declared"),
    (HANDOVER_CAPABILITY_NONE, "none"),
    (HANDOVER_CAPABILITY_UNDECLARED, "undeclared"),
)
HANDOVER_CAPABILITY_VALUES: Final[tuple[str, ...]] = (
    HANDOVER_CAPABILITY_DECLARED,
    HANDOVER_CAPABILITY_NONE,
    HANDOVER_CAPABILITY_UNDECLARED,
)
