# Generated by Django 5.2.16 on 2026-07-16 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_app_capability_and_directory_indexes'),
        ('applications', '0023_app_capability_and_directory_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('text', 'text'), ('markdown', 'markdown'), ('action_card', 'action_card')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('deeplink_url', models.CharField(blank=True, max_length=512)),
                ('dedup_key', models.CharField(blank=True, max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('biz_tag', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('completed', 'completed'), ('partially_failed', 'partially_failed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claim_token', models.CharField(blank=True, max_length=32)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('recipient_total', models.PositiveIntegerField(default=0)),
                ('recipient_sent', models.PositiveIntegerField(default=0)),
                ('recipient_failed', models.PositiveIntegerField(default=0)),
                ('requested_credential_type', models.CharField(max_length=32)),
                ('requested_credential_id', models.IntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_messages', to='applications.app')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotifyRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_ref', models.CharField(max_length=200)),
                ('dingtalk_corp_id', models.CharField(blank=True, max_length=128)),
                ('dingtalk_userid', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed'), ('throttled', 'throttled')], default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('dingtalk_task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notify.notifymessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notify_recipients', to='accounts.usermirror')),
            ],
            options={
                'ordering': ['message_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='notifymessage',
            index=models.Index(fields=['app', 'status'], name='notify_msg_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notifymessage',
            index=models.Index(fields=['app', 'created_at'], name='notify_msg_app_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notifymessage',
            index=models.Index(fields=['status', 'lease_expires_at'], name='notify_msg_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='notifymessage',
            constraint=models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('app', 'dedup_key'), name='notify_message_dedup_unique'),
        ),
        migrations.AddConstraint(
            model_name='notifymessage',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'sending', 'completed', 'partially_failed', 'failed'))), name='notify_message_status_supported'),
        ),
        migrations.AddIndex(
            model_name='notifyrecipient',
            index=models.Index(fields=['message', 'status'], name='notify_rcpt_msg_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='notifyrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('dingtalk_userid', ''), _negated=True), fields=('message', 'dingtalk_userid'), name='notify_recipient_target_unique'),
        ),
        migrations.AddConstraint(
            model_name='notifyrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'sent', 'delivered', 'failed', 'throttled'))), name='notify_recipient_status_supported'),
        ),
    ]
