# Generated by Django 5.2.16 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifymessage",
            name="deeplink_title",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
