# Generated by Django 5.2.15 on 2026-07-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0026_app_notification_channel"),
        ("notify", "0002_notifymessage_deeplink_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifymessage",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notify_messages",
                to="applications.appnotificationchannel",
            ),
        ),
    ]
