# Generated by Django 5.2.15 on 2026-07-16 14:15

from collections.abc import Iterator, Sequence
from typing import ClassVar, Protocol, Self, cast

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.operations.base import Operation


class NotificationChannelMigrationError(RuntimeError):
    pass


class _HistoricalQuery(Protocol):
    def __iter__(self) -> Iterator[object]: ...
    def filter(self, **kwargs: object) -> Self: ...
    def exclude(self, **kwargs: object) -> Self: ...
    def order_by(self, *fields: str) -> Self: ...
    def values_list(self, *fields: str, flat: bool = False) -> Self: ...
    def distinct(self) -> Self: ...
    def update(self, **kwargs: object) -> int: ...
    def exists(self) -> bool: ...


class _HistoricalModel(Protocol):
    objects: ClassVar[_HistoricalQuery]


def backfill_message_channels(
    apps: Apps,
    _schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    app = cast(
        "type[_HistoricalModel]",
        cast("object", apps.get_model("applications", "App")),
    )
    channel = cast(
        "type[_HistoricalModel]",
        cast("object", apps.get_model("applications", "AppNotificationChannel")),
    )
    message = cast(
        "type[_HistoricalModel]",
        cast("object", apps.get_model("notify", "NotifyMessage")),
    )
    app_ids = cast(
        "list[int]",
        list(message.objects.values_list("app_id", flat=True).distinct()),
    )
    if not app_ids:
        return
    channel_pairs = cast(
        "list[tuple[int, int]]",
        list(
            channel.objects.filter(
                app_id__in=app_ids,
                is_active=True,
            )
            .exclude(dingtalk_app_key="")
            .exclude(dingtalk_app_secret="")
            .exclude(agent_id="")
            .values_list("app_id", "id"),
        ),
    )
    active_channels = dict(channel_pairs)
    missing_app_ids = sorted(set(app_ids) - set(active_channels))
    if missing_app_ids:
        app_keys = cast(
            "list[str]",
            list(
                app.objects.filter(id__in=missing_app_ids)
                .order_by("app_key")
                .values_list("app_key", flat=True),
            ),
        )
        missing = "、".join(app_keys) or "未知应用"
        error_message = f"通知消息通道迁移被阻断: 应用 {missing} 缺少 active 完整通知通道。"
        raise NotificationChannelMigrationError(error_message)
    for app_id, channel_id in active_channels.items():
        _ = message.objects.filter(app_id=app_id, channel_id__isnull=True).update(
            channel_id=channel_id,
        )
    if message.objects.filter(channel_id__isnull=True).exists():
        error_message = "通知消息通道迁移被阻断: 存在无法绑定通知通道的历史消息。"
        raise NotificationChannelMigrationError(error_message)


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("applications", "0026_app_notification_channel"),
        ("notify", "0002_notifymessage_deeplink_title"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddField(
            model_name="notifymessage",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="notify_messages",
                to="applications.appnotificationchannel",
            ),
        ),
        migrations.RunPython(backfill_message_channels, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notifymessage",
            name="channel",
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name="notify_messages",
                to="applications.appnotificationchannel",
            ),
        ),
    ]
