# Generated by Django 5.2.15 on 2026-07-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_notifymessage_notify_message_counts_within_total_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notifyrecipient',
            name='notify_recipient_legacy_target_unique',
        ),
    ]
