# Generated by Django 5.2.15 on 2026-06-05 05:00

from collections.abc import Sequence
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial: ClassVar[bool | None] = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ("accounts", "0001_initial"),
        ("applications", "0001_initial"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("grant", "grant"), ("change", "change"), ("revoke", "revoke")],
                        default="grant",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("grant_applied", "grant_applied"),
                            ("grant_failed", "grant_failed"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[("timed", "timed"), ("permanent", "permanent")],
                        default="permanent",
                        max_length=16,
                    ),
                ),
                ("grant_expires_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="applications.app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="accounts.usermirror",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccessRequestPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_permissions",
                        to="access_requests.accessrequest",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_request_permissions",
                        to="applications.permission",
                    ),
                ),
            ],
            options={
                "ordering": ["access_request_id", "permission__key"],
            },
        ),
        migrations.CreateModel(
            name="AccessRequestRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_roles",
                        to="access_requests.accessrequest",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_request_roles",
                        to="applications.role",
                    ),
                ),
            ],
            options={
                "ordering": ["access_request_id", "role__key"],
            },
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_type__in", ("grant", "change", "revoke"))),
                name="access_requests_request_type_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("submitted", "approved", "rejected", "grant_applied", "grant_failed"),
                    )
                ),
                name="access_requests_status_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("grant_expires_at__isnull", False), ("grant_type", "timed")),
                    models.Q(("grant_expires_at__isnull", True), ("grant_type", "permanent")),
                    _connector="OR",
                ),
                name="access_requests_grant_expiration_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequestpermission",
            constraint=models.UniqueConstraint(
                fields=("access_request", "permission"),
                name="access_requests_request_permission_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequestrole",
            constraint=models.UniqueConstraint(
                fields=("access_request", "role"), name="access_requests_request_role_unique"
            ),
        ),
    ]
