# Generated by Django 5.2.15 on 2026-07-06 05:04

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('access_requests', '0005_accessrequest_approver_user_ids'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AddField(
            model_name='accessrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='decided_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='decision_actor_type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('console_admin', 'console_admin')], max_length=32),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
    ]
