# Generated by Django 5.2.15 on 2026-07-06 05:23

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('access_requests', '0006_accessrequest_decided_at_accessrequest_decided_by_and_more'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='dingtalk_process_instance_id',
        ),
    ]
