# Generated by Django 5.2.15 on 2026-07-26 18:37

import django.db.models.deletion
from django.db import migrations, models


def fail_on_incompatible_access_requests(apps, schema_editor):
    access_request = apps.get_model('access_requests', 'AccessRequest')
    lifecycle_count = access_request.objects.filter(
        request_type__in=('change', 'revoke', 'renew'),
    ).count()
    if lifecycle_count:
        raise RuntimeError(
            '发现缺少 base_grant_revision 的 lifecycle 申请; 请显式重建这些申请后再迁移。'
        )

    invalid_status_count = access_request.objects.exclude(
        models.Q(
            status='submitted',
            approved_at__isnull=True,
            applied_at__isnull=True,
            decided_by='',
            decision_actor_type='',
            decision_comment='',
            decided_at__isnull=True,
        )
        | models.Q(
            status='approved',
            approved_at__isnull=False,
            applied_at__isnull=True,
            decided_by__gt='',
            decision_actor_type__in=('user', 'console_admin'),
            decided_at__isnull=False,
        )
        | models.Q(
            status='rejected',
            approved_at__isnull=True,
            applied_at__isnull=True,
            decided_by__gt='',
            decision_actor_type__in=('user', 'console_admin'),
            decision_comment__gt='',
            decided_at__isnull=False,
        )
        | models.Q(
            status='grant_applied',
            approved_at__isnull=False,
            applied_at__isnull=False,
            decided_by__gt='',
            decision_actor_type__in=('user', 'console_admin'),
            decided_at__isnull=False,
        )
        | models.Q(
            status__in=('grant_failed', 'grant_expired'),
            approved_at__isnull=False,
            applied_at__isnull=True,
            decided_by__gt='',
            decision_actor_type__in=('user', 'console_admin'),
            decided_at__isnull=False,
        )
        | models.Q(
            status='withdrawn',
            approved_at__isnull=True,
            applied_at__isnull=True,
            decided_by='',
            decision_actor_type='',
            decision_comment='',
            decided_at__isnull=True,
        )
    ).count()
    if invalid_status_count:
        raise RuntimeError('发现 AccessRequest 状态字段形状非法; 请显式修复后再迁移。')


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0011_access_request_withdrawn_status'),
        ('accounts', '0015_alter_usermirror_options_and_more'),
        ('applications', '0028_alter_managedscopepolicy_options_and_more'),
        ('grants', '0006_alter_accessgrant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='base_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='grants.accessgrant'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='base_grant_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='accounts.usermirror'),
        ),
        migrations.RunPython(
            fail_on_incompatible_access_requests,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('base_grant__isnull', True), ('base_grant_revision__isnull', True), ('request_type', 'grant')), models.Q(('base_grant__isnull', False), ('base_grant_revision__isnull', False), ('request_type__in', ('change', 'revoke', 'renew'))), _connector='OR'), name='access_requests_base_grant_shape'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', True), ('decided_by', ''), ('decision_actor_type', ''), ('decision_comment', ''), ('status', 'submitted')), models.Q(('applied_at__isnull', True), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status', 'approved')), models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('decision_comment__gt', ''), ('status', 'rejected')), models.Q(('applied_at__isnull', False), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status', 'grant_applied')), models.Q(('applied_at__isnull', True), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status__in', ('grant_failed', 'grant_expired'))), models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', True), ('decided_by', ''), ('decision_actor_type', ''), ('decision_comment', ''), ('status', 'withdrawn')), _connector='OR'), name='access_requests_status_field_shape'),
        ),
    ]
