# Generated by Django 5.2.15 on 2026-07-26 19:06
# ruff: noqa: E501, Q000, RUF012
# pyright: reportAny=false, reportUnknownArgumentType=false, reportUnknownMemberType=false, reportUnknownVariableType=false, reportUnannotatedClassAttribute=false

import django.db.models.deletion
from django.db import migrations, models

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


class AccessRequestSnapshotMigrationError(RuntimeError):
    pass


def assert_no_unfinished_group_requests(
    apps: "Apps",
    schema_editor: "BaseDatabaseSchemaEditor",
) -> None:
    del apps
    cursor = schema_editor.connection.cursor()
    cursor.execute(
        """
        SELECT COUNT(*), MIN(access_request.id), MAX(access_request.id)
        FROM access_requests_accessrequest access_request
        JOIN access_requests_accessrequestgroup request_group
          ON request_group.access_request_id = access_request.id
        WHERE access_request.status IN ('submitted', 'approved', 'grant_failed')
        """,
    )
    count, min_id, max_id = cursor.fetchone()
    if count == 0:
        return
    cursor.execute(
        """
        SELECT DISTINCT access_request.id
        FROM access_requests_accessrequest access_request
        JOIN access_requests_accessrequestgroup request_group
          ON request_group.access_request_id = access_request.id
        WHERE access_request.status IN ('submitted', 'approved', 'grant_failed')
        ORDER BY access_request.id
        LIMIT 20
        """,
    )
    sample_ids = ", ".join(str(row[0]) for row in cursor.fetchall())
    message = (
        "AccessRequestGroupGrantSnapshot 迁移被阻断: 存在未完成或可重试的授权组申请, "
        "无法从当前 AuthorizationGroupGrant 安全还原提交时快照; "
        f"count={count}, request_id_range={min_id}..{max_id}, sample_ids={sample_ids}"
    )
    raise AccessRequestSnapshotMigrationError(message)


class Migration(migrations.Migration):
    dependencies = [
        ('access_requests', '0012_accessrequest_base_grant_and_more'),
    ]

    operations = [
        migrations.RunPython(assert_no_unfinished_group_requests, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AccessRequestGroupGrantSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_group_id_snapshot', models.PositiveBigIntegerField()),
                ('authorization_group_key', models.CharField(max_length=128)),
                ('authorization_group_kind', models.CharField(max_length=32)),
                ('authorization_group_name', models.CharField(max_length=255)),
                ('permission_key', models.CharField(max_length=128)),
                ('permission_name', models.CharField(max_length=255)),
                ('scope_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['access_request_id', 'authorization_group_id_snapshot', 'permission_key', 'scope_key'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='accessrequest',
            name='access_requests_status_supported',
        ),
        migrations.RemoveConstraint(
            model_name='accessrequest',
            name='access_requests_status_field_shape',
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('approved', 'approved'), ('rejected', 'rejected'), ('grant_applied', 'grant_applied'), ('grant_failed', 'grant_failed'), ('grant_conflict', 'grant_conflict'), ('grant_expired', 'grant_expired'), ('withdrawn', 'withdrawn')], default='submitted', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('submitted', 'approved', 'rejected', 'grant_applied', 'grant_failed', 'grant_conflict', 'grant_expired', 'withdrawn'))), name='access_requests_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', True), ('decided_by', ''), ('decision_actor_type', ''), ('decision_comment', ''), ('status', 'submitted')), models.Q(('applied_at__isnull', True), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status', 'approved')), models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('decision_comment__gt', ''), ('status', 'rejected')), models.Q(('applied_at__isnull', False), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status', 'grant_applied')), models.Q(('applied_at__isnull', True), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status__in', ('grant_failed', 'grant_conflict', 'grant_expired'))), models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', True), ('decided_by', ''), ('decision_actor_type', ''), ('decision_comment', ''), ('status', 'withdrawn')), _connector='OR'), name='access_requests_status_field_shape'),
        ),
        migrations.AddField(
            model_name='accessrequestgroupgrantsnapshot',
            name='access_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_grant_snapshots', to='access_requests.accessrequest'),
        ),
        migrations.AddConstraint(
            model_name='accessrequestgroupgrantsnapshot',
            constraint=models.UniqueConstraint(fields=('access_request', 'authorization_group_id_snapshot', 'permission_key', 'scope_key'), name='access_requests_group_grant_snapshot_unique'),
        ),
    ]
