# Generated by Django 5.2.15 on 2026-08-10 12:48
# SQLite 在 AddField 重建 AccessRequest 后会让 0014 的跨表 trigger 失效, 需重装。

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor

_triggers = import_module(
    "easyauth.access_requests.migrations.0014_access_request_relationship_triggers",
)


def reinstall_triggers(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    _triggers.install_triggers(apps, schema_editor)


def reverse_triggers(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    _triggers.drop_triggers(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("access_requests", "0014_access_request_relationship_triggers"),
        ("accounts", "0016_retention_indexes"),
        ("applications", "0031_app_handover_capability"),
        ("grants", "0007_access_grant_relationship_triggers"),
    ]

    operations = [
        # SQLite AddField 会重建 AccessRequest; 先拆掉 0014 触发器再改表再装回。
        migrations.RunPython(reverse_triggers, reinstall_triggers),
        migrations.AddField(
            model_name="accessrequest",
            name="approval_routing_state",
            field=models.CharField(default="normal", max_length=16),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="routing_reason",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approval_routing_state__in", ("normal", "superuser_pool")),
                ),
                name="access_requests_approval_routing_state_supported",
            ),
        ),
        migrations.RunPython(reinstall_triggers, reverse_triggers),
    ]
