# Generated by Django 5.2.15 on 2026-09-04 06:07
# SQLite 在 AddField 重建 AccessRequest 后会让 0014 的跨表 trigger 失效, 需重装。
# ruff: noqa: E501, Q000, RUF012
# pyright: reportAny=false, reportUnknownArgumentType=false, reportUnknownMemberType=false, reportUnknownVariableType=false, reportUnannotatedClassAttribute=false

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor

_triggers = import_module(
    "easyauth.access_requests.migrations.0014_access_request_relationship_triggers",
)


def reinstall_triggers(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    _triggers.install_triggers(apps, schema_editor)


def reverse_triggers(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    _triggers.drop_triggers(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0015_a1c_handover_api_approvals'),
        ('accounts', '0017_usermirror_is_console_admin'),
        ('applications', '0033_app_alias'),
        ('grants', '0007_access_grant_relationship_triggers'),
    ]

    operations = [
        # SQLite AddField 会重建 AccessRequest; 先拆掉 0014 触发器再改表再装回。
        migrations.RunPython(reverse_triggers, reinstall_triggers),
        migrations.RemoveConstraint(
            model_name='accessrequest',
            name='access_requests_status_field_shape',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='申请人撤回该申请的时刻; 仅 status=withdrawn 时填写。', null=True),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', True), ('decided_by', ''), ('decision_actor_type', ''), ('decision_comment', ''), ('status', 'submitted'), ('withdrawn_at__isnull', True)), models.Q(('applied_at__isnull', True), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status', 'approved'), ('withdrawn_at__isnull', True)), models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('decision_comment__gt', ''), ('status', 'rejected'), ('withdrawn_at__isnull', True)), models.Q(('applied_at__isnull', False), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status', 'grant_applied'), ('withdrawn_at__isnull', True)), models.Q(('applied_at__isnull', True), ('approved_at__isnull', False), ('decided_at__isnull', False), ('decided_by__gt', ''), ('decision_actor_type__in', ('user', 'console_admin')), ('status__in', ('grant_failed', 'grant_conflict', 'grant_expired')), ('withdrawn_at__isnull', True)), models.Q(('applied_at__isnull', True), ('approved_at__isnull', True), ('decided_at__isnull', True), ('decided_by', ''), ('decision_actor_type', ''), ('decision_comment', ''), ('status', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='access_requests_status_field_shape'),
        ),
        migrations.RunPython(reinstall_triggers, reverse_triggers),
    ]
