# Generated by Django 5.2.15 on 2026-07-06 05:19

import django.db.models.deletion
import easyauth.config.crypto
from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial: ClassVar[bool | None] = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = [
        ('applications', '0019_integrationsettings_dingtalk_agent_id_and_more'),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name='AppWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', easyauth.config.crypto.EncryptedCharField(blank=True, max_length=1024)),
                ('enabled', models.BooleanField(default=True)),
                ('approval_callback_url', models.CharField(blank=True, max_length=512)),
                ('handover_url', models.CharField(blank=True, max_length=512)),
                ('onboard_url', models.CharField(blank=True, max_length=512)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to='applications.app')),
            ],
            options={
                'ordering': ['app__app_key'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('target_url', models.CharField(max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('failed', 'failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='applications.app')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'delivered', 'failed'))), name='webhooks_delivery_status_supported')],
            },
        ),
    ]
