# Generated by Django 5.2.15 on 2026-07-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_notification_channel_directory_scope'),
        ('webhooks', '0002_webhook_transport_and_delivery_claim'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'lease_expires_at'], name='webhooks_delivery_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_token', ''), ('lease_expires_at__isnull', True), ('status', 'pending')), models.Q(('status', 'pending'), models.Q(('claim_token', ''), _negated=True), ('lease_expires_at__isnull', False)), models.Q(models.Q(('status', 'pending'), _negated=True), ('claim_token', ''), ('lease_expires_at__isnull', True)), _connector='OR'), name='webhooks_delivery_lease_shape_valid'),
        ),
    ]
