# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0003_webhookdelivery_webhooks_delivery_lease_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdelivery",
            name="payload_minimized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="payload_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["app", "status", "-created_at", "-id"],
                name="webhook_deliv_app_stat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "payload_minimized_at", "updated_at", "id"],
                name="webhook_deliv_retention_idx",
            ),
        ),
    ]
