# Generated by Django 5.2.15 on 2026-08-11 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_raw_payload_minimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
