# Generated by Django 5.2.15 on 2026-09-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0006_appwebhookconfig_events_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appwebhookconfig",
            name="events_url",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
