#!/usr/bin/env python3
"""Read-only code health scanner for EasyAuth."""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


CODE_SUFFIXES = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".css",
    ".scss",
    ".html",
}
PY_SUFFIXES = {".py"}
TS_SUFFIXES = {".js", ".jsx", ".ts", ".tsx"}
DEFAULT_EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".cache",
    ".mypy_cache",
    ".omx",
    ".pytest_cache",
    ".ruff_cache",
    ".tools",
    ".tox",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "htmlcov",
    "migrations",
    "node_modules",
}
DEFAULT_EXCLUDED_PATH_PARTS = {
    ("src", "easyauth", "static", "easyauth", "frontend"),
    ("frontend", "dist"),
    ("frontend", "coverage"),
}
GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "generated by",
    "do not edit",
)
COMMENT_PREFIXES = {
    ".py": ("#",),
    ".js": ("//", "/*", "*", "*/"),
    ".jsx": ("//", "/*", "*", "*/"),
    ".ts": ("//", "/*", "*", "*/"),
    ".tsx": ("//", "/*", "*", "*/"),
    ".css": ("/*", "*", "*/"),
    ".scss": ("/*", "*", "*/"),
    ".html": ("<!--", "-->"),
}
IMPORT_RE = re.compile(r"""(?:import\s+(?:.+?\s+from\s+)?|export\s+.+?\s+from\s+)["']([^"']+)["']""")
REQUIRE_RE = re.compile(r"""require\(["']([^"']+)["']\)""")
FUNCTION_PATTERNS = (
    re.compile(r"\bfunction\s+([A-Za-z_$][\w$]*)\s*\("),
    re.compile(r"\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>"),
    re.compile(r"\b([A-Za-z_$][\w$]*)\s*:\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>"),
)
CLASS_RE = re.compile(r"\bclass\s+([A-Za-z_$][\w$]*)\b")


@dataclass(frozen=True)
class CodeFile:
    path: Path
    relpath: str
    lines: list[str]


@dataclass(frozen=True)
class SymbolMetric:
    kind: str
    name: str
    path: str
    start_line: int
    end_line: int
    raw_loc: int
    sloc: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scan repository code health metrics.")
    parser.add_argument("--root", default=".", help="Repository root to scan.")
    parser.add_argument("--output", help="Write output to this file instead of stdout.")
    parser.add_argument(
        "--format",
        choices=("json", "markdown"),
        default="json",
        help="Output format. JSON includes markdown_summary.",
    )
    parser.add_argument(
        "--duplicate-window",
        type=int,
        default=8,
        help="Number of normalized non-empty lines in a duplicate fragment.",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=20,
        help="Maximum rows for ranked sections.",
    )
    return parser.parse_args()


def is_within_parts(parts: tuple[str, ...], candidate: tuple[str, ...]) -> bool:
    if len(candidate) > len(parts):
        return False
    return any(parts[index : index + len(candidate)] == candidate for index in range(len(parts) - len(candidate) + 1))


def should_skip_path(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    parts = rel.parts
    if any(part in DEFAULT_EXCLUDED_DIRS for part in parts):
        return True
    if any(part.endswith("-venv") or part.endswith("_venv") for part in parts):
        return True
    return any(is_within_parts(parts, excluded) for excluded in DEFAULT_EXCLUDED_PATH_PARTS)


def looks_generated(lines: list[str]) -> bool:
    head = "\n".join(lines[:20]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def iter_code_files(root: Path) -> Iterable[CodeFile]:
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix not in CODE_SUFFIXES:
            continue
        if should_skip_path(path, root):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        lines = text.splitlines()
        if looks_generated(lines):
            continue
        yield CodeFile(path=path, relpath=path.relative_to(root).as_posix(), lines=lines)


def is_sloc(line: str, suffix: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    return not any(stripped.startswith(prefix) for prefix in COMMENT_PREFIXES.get(suffix, ()))


def count_sloc(lines: Iterable[str], suffix: str) -> int:
    return sum(1 for line in lines if is_sloc(line, suffix))


def end_line(node: ast.AST) -> int:
    return int(getattr(node, "end_lineno", getattr(node, "lineno", 1)))


def scan_python_symbols(code_file: CodeFile) -> list[SymbolMetric]:
    try:
        tree = ast.parse("\n".join(code_file.lines), filename=code_file.relpath)
    except SyntaxError:
        return []

    symbols: list[SymbolMetric] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            start = int(node.lineno)
            end = end_line(node)
            snippet = code_file.lines[start - 1 : end]
            kind = "class" if isinstance(node, ast.ClassDef) else "function"
            symbols.append(
                SymbolMetric(
                    kind=kind,
                    name=node.name,
                    path=code_file.relpath,
                    start_line=start,
                    end_line=end,
                    raw_loc=end - start + 1,
                    sloc=count_sloc(snippet, ".py"),
                )
            )
    return symbols


def find_matching_brace(lines: list[str], start_index: int, start_column: int) -> int:
    depth = 0
    seen_open = False
    in_string: str | None = None
    escaped = False
    for line_index in range(start_index, len(lines)):
        line = lines[line_index]
        column = start_column if line_index == start_index else 0
        while column < len(line):
            char = line[column]
            if in_string:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == in_string:
                    in_string = None
            elif char in ("'", '"', "`"):
                in_string = char
            elif char == "{":
                depth += 1
                seen_open = True
            elif char == "}":
                depth -= 1
                if seen_open and depth == 0:
                    return line_index + 1
            column += 1
    return start_index + 1


def scan_braced_symbols(code_file: CodeFile) -> list[SymbolMetric]:
    text = "\n".join(code_file.lines)
    line_starts = [0]
    for match in re.finditer("\n", text):
        line_starts.append(match.end())

    def line_for_offset(offset: int) -> tuple[int, int]:
        low = 0
        high = len(line_starts)
        while low + 1 < high:
            mid = (low + high) // 2
            if line_starts[mid] <= offset:
                low = mid
            else:
                high = mid
        return low + 1, offset - line_starts[low]

    symbols: list[SymbolMetric] = []
    seen: set[tuple[str, str, int]] = set()
    for kind, patterns in (("class", (CLASS_RE,)), ("function", FUNCTION_PATTERNS)):
        for pattern in patterns:
            for match in pattern.finditer(text):
                brace = text.find("{", match.end())
                if brace == -1:
                    continue
                start_line, start_column = line_for_offset(match.start())
                brace_line, brace_column = line_for_offset(brace)
                end = find_matching_brace(code_file.lines, brace_line - 1, brace_column)
                name = match.group(1)
                key = (kind, name, start_line)
                if key in seen:
                    continue
                seen.add(key)
                snippet = code_file.lines[start_line - 1 : end]
                symbols.append(
                    SymbolMetric(
                        kind=kind,
                        name=name,
                        path=code_file.relpath,
                        start_line=start_line,
                        end_line=end,
                        raw_loc=end - start_line + 1,
                        sloc=count_sloc(snippet, code_file.path.suffix),
                    )
                )
    return symbols


def scan_symbols(code_files: Iterable[CodeFile]) -> list[SymbolMetric]:
    symbols: list[SymbolMetric] = []
    for code_file in code_files:
        if code_file.path.suffix in PY_SUFFIXES:
            symbols.extend(scan_python_symbols(code_file))
        elif code_file.path.suffix in TS_SUFFIXES:
            symbols.extend(scan_braced_symbols(code_file))
    return symbols


def python_imports(code_file: CodeFile) -> set[str]:
    try:
        tree = ast.parse("\n".join(code_file.lines), filename=code_file.relpath)
    except SyntaxError:
        return set()
    imports: set[str] = set()
    package_parts = code_file.relpath.removesuffix(".py").split("/")[:-1]
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                base = package_parts[: max(0, len(package_parts) - node.level + 1)]
                if node.module:
                    base.extend(node.module.split("."))
                imports.add(".".join(part for part in base if part))
            elif node.module:
                imports.add(node.module)
    return imports


def ts_imports(code_file: CodeFile) -> set[str]:
    text = "\n".join(code_file.lines)
    imports = {match.group(1) for match in IMPORT_RE.finditer(text)}
    imports.update(match.group(1) for match in REQUIRE_RE.finditer(text))
    return imports


def module_candidates(code_files: Iterable[CodeFile], root: Path) -> dict[str, str]:
    modules: dict[str, str] = {}
    for code_file in code_files:
        rel = Path(code_file.relpath)
        if code_file.path.suffix == ".py":
            module = ".".join(rel.with_suffix("").parts)
            if module.endswith(".__init__"):
                module = module[: -len(".__init__")]
            modules[module] = code_file.relpath
            if module.startswith("src."):
                modules[module.removeprefix("src.")] = code_file.relpath
        elif code_file.path.suffix in TS_SUFFIXES:
            stem = rel.with_suffix("").as_posix()
            modules[stem] = code_file.relpath
            modules[f"./{stem}"] = code_file.relpath
            modules[root.joinpath(rel).with_suffix("").as_posix()] = code_file.relpath
    return modules


def resolve_ts_import(import_path: str, importer: CodeFile, files_by_rel: dict[str, CodeFile]) -> str | None:
    if not import_path.startswith("."):
        return None
    base = Path(importer.relpath).parent.joinpath(import_path)
    candidates = [base]
    candidates.extend(base.with_suffix(suffix) for suffix in TS_SUFFIXES)
    candidates.extend(base.joinpath(f"index{suffix}") for suffix in TS_SUFFIXES)
    for candidate in candidates:
        rel = candidate.as_posix()
        if rel in files_by_rel:
            return rel
    return None


def resolve_python_import(import_path: str, modules: dict[str, str]) -> str | None:
    parts = import_path.split(".")
    while parts:
        candidate = ".".join(parts)
        if candidate in modules:
            return modules[candidate]
        parts.pop()
    return None


def scan_dependencies(code_files: list[CodeFile], root: Path) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    files_by_rel = {code_file.relpath: code_file for code_file in code_files}
    modules = module_candidates(code_files, root)
    fan_out: dict[str, set[str]] = defaultdict(set)
    fan_in: dict[str, set[str]] = defaultdict(set)

    for code_file in code_files:
        deps: set[str] = set()
        if code_file.path.suffix in PY_SUFFIXES:
            for imported in python_imports(code_file):
                resolved = resolve_python_import(imported, modules)
                if resolved and resolved != code_file.relpath:
                    deps.add(resolved)
        elif code_file.path.suffix in TS_SUFFIXES:
            for imported in ts_imports(code_file):
                resolved = resolve_ts_import(imported, code_file, files_by_rel)
                if resolved and resolved != code_file.relpath:
                    deps.add(resolved)
        fan_out[code_file.relpath].update(deps)
        for dep in deps:
            fan_in[dep].add(code_file.relpath)

    return (
        {path: sorted(deps) for path, deps in fan_out.items()},
        {path: sorted(refs) for path, refs in fan_in.items()},
    )


def normalize_duplicate_line(line: str) -> str:
    return re.sub(r"\s+", " ", line.strip())


def scan_duplicates(code_files: Iterable[CodeFile], window: int, top: int) -> list[dict[str, object]]:
    fragments: dict[tuple[str, ...], list[dict[str, object]]] = defaultdict(list)
    for code_file in code_files:
        normalized = [
            (index + 1, normalize_duplicate_line(line))
            for index, line in enumerate(code_file.lines)
            if normalize_duplicate_line(line)
            and not any(normalize_duplicate_line(line).startswith(prefix) for prefix in COMMENT_PREFIXES.get(code_file.path.suffix, ()))
        ]
        if len(normalized) < window:
            continue
        for index in range(len(normalized) - window + 1):
            chunk = normalized[index : index + window]
            key = tuple(line for _, line in chunk)
            fragments[key].append(
                {
                    "path": code_file.relpath,
                    "start_line": chunk[0][0],
                    "end_line": chunk[-1][0],
                }
            )

    duplicates = [
        {
            "lines": list(fragment),
            "occurrences": occurrences,
            "occurrence_count": len(occurrences),
        }
        for fragment, occurrences in fragments.items()
        if len({item["path"] for item in occurrences}) > 1 or len(occurrences) > 1
    ]
    duplicates.sort(key=lambda item: (-int(item["occurrence_count"]), str(item["occurrences"][0]["path"])))
    return duplicates[:top]


def ranked_symbols(symbols: Iterable[SymbolMetric], kind: str, top: int) -> list[dict[str, object]]:
    filtered = [symbol for symbol in symbols if symbol.kind == kind]
    filtered.sort(key=lambda symbol: (-symbol.sloc, symbol.path, symbol.start_line))
    return [
        {
            "name": symbol.name,
            "path": symbol.path,
            "start_line": symbol.start_line,
            "end_line": symbol.end_line,
            "raw_loc": symbol.raw_loc,
            "sloc": symbol.sloc,
        }
        for symbol in filtered[:top]
    ]


def ranked_dependencies(deps: dict[str, list[str]], top: int) -> list[dict[str, object]]:
    rows = [{"path": path, "count": len(values), "files": values} for path, values in deps.items() if values]
    rows.sort(key=lambda item: (-int(item["count"]), str(item["path"])))
    return rows[:top]


def build_markdown(result: dict[str, object]) -> str:
    summary = result["summary"]
    assert isinstance(summary, dict)
    lines = [
        "# EasyAuth 代码健康扫描摘要",
        "",
        "## 总览",
        "",
        f"- 扫描根目录：`{result['root']}`",
        f"- 文件数：{summary['file_count']}",
        f"- Raw LOC：{summary['raw_loc']}",
        f"- SLOC：{summary['sloc']}",
        f"- 函数数：{summary['function_count']}",
        f"- Class 数：{summary['class_count']}",
        f"- 重复 {summary['duplicate_window']} 行片段数：{summary['duplicate_fragment_count']}",
        "",
        "## 最长函数",
        "",
    ]
    for item in result["top_functions"]:
        lines.append(f"- `{item['path']}:{item['start_line']}` `{item['name']}`：{item['sloc']} SLOC")
    lines.extend(["", "## 最长 class", ""])
    for item in result["top_classes"]:
        lines.append(f"- `{item['path']}:{item['start_line']}` `{item['name']}`：{item['sloc']} SLOC")
    lines.extend(["", "## fan-out 最高文件", ""])
    for item in result["top_fan_out"]:
        lines.append(f"- `{item['path']}`：{item['count']}")
    lines.extend(["", "## fan-in 最高文件", ""])
    for item in result["top_fan_in"]:
        lines.append(f"- `{item['path']}`：{item['count']}")
    lines.extend(["", "## 重复片段", ""])
    for item in result["duplicate_fragments"][:10]:
        occurrences = ", ".join(f"`{occ['path']}:{occ['start_line']}`" for occ in item["occurrences"][:5])
        lines.append(f"- 出现 {item['occurrence_count']} 次：{occurrences}")
    return "\n".join(lines) + "\n"


def build_result(root: Path, duplicate_window: int, top: int) -> dict[str, object]:
    code_files = list(iter_code_files(root))
    symbols = scan_symbols(code_files)
    fan_out, fan_in = scan_dependencies(code_files, root)
    duplicate_fragments = scan_duplicates(code_files, duplicate_window, top)
    suffix_counts = Counter(code_file.path.suffix for code_file in code_files)

    result: dict[str, object] = {
        "root": root.as_posix(),
        "summary": {
            "file_count": len(code_files),
            "raw_loc": sum(len(code_file.lines) for code_file in code_files),
            "sloc": sum(count_sloc(code_file.lines, code_file.path.suffix) for code_file in code_files),
            "function_count": sum(1 for symbol in symbols if symbol.kind == "function"),
            "class_count": sum(1 for symbol in symbols if symbol.kind == "class"),
            "duplicate_window": duplicate_window,
            "duplicate_fragment_count": len(duplicate_fragments),
        },
        "files_by_suffix": dict(sorted(suffix_counts.items())),
        "top_functions": ranked_symbols(symbols, "function", top),
        "top_classes": ranked_symbols(symbols, "class", top),
        "top_fan_out": ranked_dependencies(fan_out, top),
        "top_fan_in": ranked_dependencies(fan_in, top),
        "duplicate_fragments": duplicate_fragments,
        "excluded": {
            "directories": sorted(DEFAULT_EXCLUDED_DIRS),
            "path_parts": ["/".join(parts) for parts in sorted(DEFAULT_EXCLUDED_PATH_PARTS)],
            "generated_markers": list(GENERATED_MARKERS),
        },
    }
    result["markdown_summary"] = build_markdown(result)
    return result


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    if not root.exists() or not root.is_dir():
        print(f"error: root is not a directory: {root}", file=sys.stderr)
        return 2
    if args.duplicate_window < 2:
        print("error: --duplicate-window must be at least 2", file=sys.stderr)
        return 2
    if args.top < 1:
        print("error: --top must be at least 1", file=sys.stderr)
        return 2

    result = build_result(root, args.duplicate_window, args.top)
    if args.format == "json":
        output = json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    else:
        output = str(result["markdown_summary"])

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
    else:
        sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
