# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["created_at", "id"], name="audit_log_retention_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "-created_at", "-id"],
                name="audit_log_event_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor_type", "actor_id", "-created_at"],
                name="audit_log_actor_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_type", "target_id", "-created_at"],
                name="audit_log_target_idx",
            ),
        ),
    ]
