# Generated by Django 5.2 on 2026-07-10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=255, unique=True)),
                ("task_name", models.CharField(max_length=255)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发布"),
                            ("in_flight", "发布中"),
                            ("published", "已发布"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_token", models.CharField(blank=True, max_length=32)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"],
                        name="outbox_status_available_idx",
                    ),
                    models.Index(
                        fields=["status", "lease_expires_at"],
                        name="outbox_status_lease_idx",
                    ),
                ],
            },
        ),
    ]
