# Generated by Django 5.2.15 on 2026-07-26 18:35

from django.db import migrations, models
from django.db.models import Max, Min, Q


def _fail_if_invalid_outbox_events(apps, _schema_editor):
    outbox_event = apps.get_model("outbox", "OutboxEvent")
    valid_shape = (
        Q(status__in=("pending", "in_flight", "published"))
        & (
            Q(
                status="pending",
                lease_token="",
                lease_expires_at__isnull=True,
                published_at__isnull=True,
            )
            | Q(
                status="in_flight",
                lease_token__gt="",
                lease_expires_at__isnull=False,
                last_error="",
                published_at__isnull=True,
            )
            | Q(
                status="published",
                lease_token="",
                lease_expires_at__isnull=True,
                last_error="",
                published_at__isnull=False,
            )
        )
    )
    invalid = outbox_event.objects.exclude(valid_shape)
    invalid_count = invalid.count()
    if invalid_count:
        bounds = invalid.aggregate(min_pk=Min("pk"), max_pk=Max("pk"))
        raise RuntimeError(
            "OutboxEvent 状态机存在非法历史数据, 已拒绝继续迁移: "
            f"count={invalid_count}, pk_range={bounds['min_pk']}..{bounds['max_pk']}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            _fail_if_invalid_outbox_events,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'in_flight', 'published'))), name='outbox_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', True), ('lease_token', ''), ('published_at__isnull', True), ('status', 'pending')), models.Q(('last_error', ''), ('lease_expires_at__isnull', False), ('lease_token__gt', ''), ('published_at__isnull', True), ('status', 'in_flight')), models.Q(('last_error', ''), ('lease_expires_at__isnull', True), ('lease_token', ''), ('published_at__isnull', False), ('status', 'published')), _connector='OR'), name='outbox_state_truth_shape'),
        ),
    ]
