"""外部 URL/主机校验门面: 公开符号再导出。"""

from __future__ import annotations

from easyauth.config.net_dns import (
    DNS_RESOLUTION_TIMEOUT_MESSAGE,
    DNS_RESOLVER_MAX_IN_FLIGHT,
    DNS_RESOLVER_QUEUE_FULL_MESSAGE,
    DNS_RESOLVER_SCRIPT,
    resolve_public_addresses,
)
from easyauth.config.net_errors import (
    BLOCKED_HOST_MESSAGE,
    UNRESOLVABLE_HOST_MESSAGE,
    BlockedHostError,
)
from easyauth.config.net_http import (
    HTTP_INVALID_CONTENT_LENGTH_MESSAGE,
    HTTP_RESPONSE_DEADLINE_MESSAGE,
    HTTP_RESPONSE_TOO_LARGE_MESSAGE,
    HeaderReadableResponse,
    HttpResponseDeadlineExceededError,
    HttpResponseReadError,
    HttpResponseTooLargeError,
    InvalidContentLengthError,
    read_urlopen_body_bounded,
)
from easyauth.config.net_policy import (
    E2E_ALLOW_INSECURE_WEBHOOK_HOSTS_ENV,
    E2E_RUNTIME_SETTINGS_MODULE,
    INSECURE_URL_MESSAGE,
    INVALID_WEBHOOK_URL_MESSAGE,
    LOCAL_HTTP_HOSTS,
    WEBHOOK_HOST_NOT_ALLOWED_MESSAGE,
    InsecureUrlError,
    InvalidWebhookUrlError,
    ValidatedHttpsUrl,
    assert_public_host,
    e2e_allowed_insecure_webhook_hosts,
    is_e2e_insecure_webhook_host,
    normalize_hostname,
    parse_https_url,
    require_secure_url,
    validate_public_https_url,
)

__all__ = (
    "BLOCKED_HOST_MESSAGE",
    "DNS_RESOLUTION_TIMEOUT_MESSAGE",
    "DNS_RESOLVER_MAX_IN_FLIGHT",
    "DNS_RESOLVER_QUEUE_FULL_MESSAGE",
    "DNS_RESOLVER_SCRIPT",
    "E2E_ALLOW_INSECURE_WEBHOOK_HOSTS_ENV",
    "E2E_RUNTIME_SETTINGS_MODULE",
    "HTTP_INVALID_CONTENT_LENGTH_MESSAGE",
    "HTTP_RESPONSE_DEADLINE_MESSAGE",
    "HTTP_RESPONSE_TOO_LARGE_MESSAGE",
    "INSECURE_URL_MESSAGE",
    "INVALID_WEBHOOK_URL_MESSAGE",
    "LOCAL_HTTP_HOSTS",
    "UNRESOLVABLE_HOST_MESSAGE",
    "WEBHOOK_HOST_NOT_ALLOWED_MESSAGE",
    "BlockedHostError",
    "HeaderReadableResponse",
    "HttpResponseDeadlineExceededError",
    "HttpResponseReadError",
    "HttpResponseTooLargeError",
    "InsecureUrlError",
    "InvalidContentLengthError",
    "InvalidWebhookUrlError",
    "ValidatedHttpsUrl",
    "assert_public_host",
    "e2e_allowed_insecure_webhook_hosts",
    "is_e2e_insecure_webhook_host",
    "normalize_hostname",
    "parse_https_url",
    "read_urlopen_body_bounded",
    "require_secure_url",
    "resolve_public_addresses",
    "validate_public_https_url",
)
